/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : test
Source Server Version : 110200
Source Host           : localhost:1521
Source Schema         : VOTE

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-11-13 09:42:24
*/


-- ----------------------------
-- Table structure for CODE_DATA
-- ----------------------------
DROP TABLE "VOTE"."CODE_DATA";
CREATE TABLE "VOTE"."CODE_DATA" (
"FIELD_NAME" VARCHAR2(54 BYTE) NULL ,
"CODE_NO" VARCHAR2(64 BYTE) NOT NULL ,
"CODE_NAME" VARCHAR2(64 BYTE) NULL ,
"CODE_KEY" VARCHAR2(80 BYTE) NOT NULL ,
"CODE_VAL" VARCHAR2(125 BYTE) NULL ,
"TM_SMP" VARCHAR2(14 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "VOTE"."CODE_DATA" IS '数据字典';
COMMENT ON COLUMN "VOTE"."CODE_DATA"."FIELD_NAME" IS '字段名称';
COMMENT ON COLUMN "VOTE"."CODE_DATA"."CODE_NO" IS '字典类型编码';
COMMENT ON COLUMN "VOTE"."CODE_DATA"."CODE_NAME" IS '字典类型说明';
COMMENT ON COLUMN "VOTE"."CODE_DATA"."CODE_KEY" IS '字典代码';
COMMENT ON COLUMN "VOTE"."CODE_DATA"."CODE_VAL" IS '字典名称';
COMMENT ON COLUMN "VOTE"."CODE_DATA"."TM_SMP" IS '创建时间';

-- ----------------------------
-- Records of CODE_DATA
-- ----------------------------
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditInfoFrom', 'CreditInfoFrom', '不良信息来源', '07', '其他渠道', '2018-03-14');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditInfoFrom', 'CreditInfoFrom', '不良信息来源', '06', '街道办事处提出的记分建议', '2018-03-14');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('APP_TYPE', 'APP_TYPE', '流程类型', 'CREDITRECORDBL', '不良信息建档流程', '2018-03-27');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EXPERT_TYPE', 'EXPERT_TYPE', '评标专家类型', '03', '执业律师', '2018-03-29');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EXPERT_TYPE', 'EXPERT_TYPE', '评标专家类型', '01', '管理类', '2018-03-29');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EXPERT_TYPE', 'EXPERT_TYPE', '评标专家类型', '02', '技术类', '2018-03-29');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EXPERT_TYPE', 'EXPERT_TYPE', '评标专家类型', '04', '招标人代表', '2018-03-29');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EXPERT_TYPE', 'EXPERT_TYPE', '评标专家类型', '05', '物业管理专家学者', '2018-03-29');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EXPERT_TYPE', 'EXPERT_TYPE', '评标专家类型', '06', '业主委员会委员', '2018-03-29');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EXPERT_TYPE', 'EXPERT_TYPE', '评标专家类型', '07', '物业管理行业优秀企业家', '2018-03-29');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EXPERT_TYPE', 'EXPERT_TYPE', '评标专家类型', '08', '其它', '2018-03-29');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('USER_STATUS', 'USER_STATUS', '用户状态', '1', '正在使用', '2018-01-31');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditQuotaKind', 'CreditQuotaKind', '诚信指标类型', '01', '良好信用指标', '2018-03-05');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditQuotaKind', 'CreditQuotaKind', '诚信指标类型', '02', '不良信用指标', '2018-03-05');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('WAS_USEFUL', 'WAS_USEFUL', '是否有效', '无效', '无效', '2018-03-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditInfoFrom', 'CreditInfoFrom', '不良信息来源', '05', '相关行政机关下达的行政处罚决定书', '2018-03-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditBadRecordKind', 'CreditBadRecordKind', '不良信息类型', '03', '违反物业服务合同约定，经查证属实的', '2018-03-14');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditBadRecordKind', 'CreditBadRecordKind', '不良信息类型', '04', '社会公众和媒体曝光，造成恶劣影响的或业主合理投诉得不到有效解决的信息', '2018-03-14');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditBadRecordKind', 'CreditBadRecordKind', '不良信息类型', '05', '房屋主管部门认定可记录的其他信息', '2018-03-14');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('APP_TYPE', 'APP_TYPE', '流程类型', 'CSPADDFLOW', '物业公司信息采集', '2018-02-11');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('PRODUCT_TYPE', 'PRODUCT_TYPE', '产品类型', '01', '大数据', '2018-03-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('IS_USEFUL', 'IS_USEFUL', '是否有效', '01', '无效', '2018-03-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('WAS_USEFUL', 'WAS_USEFUL', '是否有效', '有效', '有效', '2018-03-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_TYPE', 'ORG_TYPE', '机构类型', '07', '6级组织', '2018-03-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_TYPE', 'ORG_TYPE', '机构类型', '08', '7级组织', '2018-03-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_TYPE', 'ORG_TYPE', '机构类型', '06', '5级组织', '2018-11-03');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('APP_TYPE', 'APP_TYPE', '流程类型', 'CSPXGFLOW', '物业公司信息变更', '2018-02-24');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('APP_TYPE', 'APP_TYPE', '流程类型', 'CSPDELFLOW', '物业公司信息删除', '2018-03-01');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('INFO_STATUS', 'INFO_STATUS', '数据状态', '00', '正常', '2018-02-08');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('INFO_STATUS', 'INFO_STATUS', '数据状态', '01', '暂存', '2018-02-08');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('INFO_STATUS', 'INFO_STATUS', '数据状态', '02', '修改中', '2018-02-08');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('INFO_STATUS', 'INFO_STATUS', '数据状态', '03', '删除中', '2018-02-08');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('INFO_STATUS', 'INFO_STATUS', '数据状态', '04', '已注销', '2018-02-08');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('APP_TYPE', 'APP_TYPE', '流程类型', 'SECTEDITFLOW', '项目信息修改流程', '2018-02-26');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('NORM_TYPE', 'NORM_TYPE', '指标类型', '01', '星级小区创建', '2018-02-27');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('NORM_TYPE', 'NORM_TYPE', '指标类型', '02', '社会信誉', '2018-02-27');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('NORM_LEVEL', 'NORM_LEVEL', '指标层级', '1', '一级指标', '2018-02-27');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('NORM_LEVEL', 'NORM_LEVEL', '指标层级', '2', '二级指标', '2018-02-27');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('NORM_RECORD', 'NORM_RECORD', '指标记分标志', '0', '减分', '2018-02-27');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('NORM_RECORD', 'NORM_RECORD', '指标记分标志', '1', '加分', '2018-02-27');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('APP_TYPE1', 'APP_TYPE', '流程类型', 'CREDITAPPEAL', '不良信用异议申请流程', '2018-10-19');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CUST_TYPE', 'CUST_TYPE', '客户类型', '00', 'Blank', '2018-10-28');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CUST_TYPE', 'CUST_TYPE', '客户类型', '01', 'Paper', '2018-10-28');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CUST_TYPE', 'CUST_TYPE', '客户类型', '02', 'Copper', '2018-10-28');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CUST_TYPE', 'CUST_TYPE', '客户类型', '03', 'Diamond', '2018-10-28');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CUST_TYPE', 'CUST_TYPE', '客户类型', '04', 'Silver', '2018-10-28');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CUST_TRADE', 'CUST_TRADE', '客户行业', '01', '金融', '2018-10-28');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('PAY_CYCLE', 'PAY_CYCLE', '结算周期', '01', '季结（90天）结算周期', '2018-10-28');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('BG_VISIABLE', 'BG_VISIABLE', 'BG隐藏', '01', '金融解决方案业务部', '2018-10-28');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('IS_USEFUL', 'IS_USEFUL', '是否有效', '00', '有效', '2018-10-28');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('COUNTRY', 'COUNTRY', '国家/地区', '00', '中国', '2018-10-29');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('COUNTRY', 'COUNTRY', '国家/地区', '01', '中国/香港', '2018-10-29');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('menu_list', 'MENU_LIST', '菜单级别', '2', '二级菜单', '20170504');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('menu_list', 'MENU_LIST', '菜单级别', '1', '一级菜单', '20170504');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('PARAMS_TYPE', 'PARAMS_TYPE', '参数类型', '01', '系统参数', '20180125');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('PARAMS_TYPE', 'PARAMS_TYPE', '参数类型', '02', '业务参数', '20180125');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CURR_STATUS', 'CURR_STATUS', '流程状态', '04', '已驳回', '20180109');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CURR_STATUS', 'CURR_STATUS', '流程状态', '03', '已结束', '20180109');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CURR_STATUS', 'CURR_STATUS', '流程状态', '02', '审核中', '20180109');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CURR_STATUS', 'CURR_STATUS', '流程状态', '05', '会签', '20180123');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CURR_STATUS', 'CURR_STATUS', '流程状态', '01', '已启动', '20180109');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CURR_STATUS', 'CURR_STATUS', '流程状态', '00', '待启动', '20180109');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('TASK_TYPE', 'TASK_TYPE', '任务类型', '00', '启动', '2018-02-02');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('TASK_TYPE', 'TASK_TYPE', '任务类型', '01', '提交下一步', '2018-02-02');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('TASK_TYPE', 'TASK_TYPE', '任务类型', '02', '驳回', '2018-02-02');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('TASK_TYPE', 'TASK_TYPE', '任务类型', '03', '提交会签', '2018-02-02');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('TASK_TYPE', 'TASK_TYPE', '任务类型', '05', '结束', '2018-02-02');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('FILE_TYPE', 'FILE_TYPE', '附件类型', '00', '鉴定申请表', '20180125');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('FILE_TYPE', 'FILE_TYPE', '附件类型', '01', '房屋所有权证材料复印件', '20180125');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('FILE_TYPE', 'FILE_TYPE', '附件类型', '99', '其他', '20171219');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('FILE_TYPE', 'FILE_TYPE', '附件类型', '05', '连云港市危房和老旧房屋鉴定申请表', '20180125');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('FILE_TYPE', 'FILE_TYPE', '附件类型', '04', '法律法规规定应当提供的其他资料', '20180125');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('FILE_TYPE', 'FILE_TYPE', '附件类型', '02', '房屋建筑施工图、结构施工图、历经改造的施工技术资料', '20180125');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('FILE_TYPE', 'FILE_TYPE', '附件类型', '03', '房屋所有权人的身份证复印件', '20180125');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('REGION_TYPE', 'REGION_TYPE', '区域级别', '02', '县', '20170523');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('REGION_TYPE', 'REGION_TYPE', '区域级别', '01', '区', '20170523');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_TYPE', 'ORG_TYPE', '机构类型', '05', '4级组织', '2018-11-03');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_TYPE', 'ORG_TYPE', '机构类型', '04', '3级组织', '2018-11-03');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_TYPE', 'ORG_TYPE', '机构类型', '03', '2级组织', '2018-11-03');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_TYPE', 'ORG_TYPE', '机构类型', '02', '1级组织', '2018-11-03');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_TYPE', 'ORG_TYPE', '机构类型', '01', '0级组织', '2018-11-03');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_NATURE', 'ORG_NATURE', '企业性质', '01', '全民所有制', '2018-01-31');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_NATURE', 'ORG_NATURE', '企业性质', '02', '有限责任公司', '2018-01-31');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_NATURE', 'ORG_NATURE', '企业性质', '03', '股份有限公司', '2018-01-31');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CSP_LEVEL', 'CSP_LEVEL', '资质等级', '1', '一级资质', '2018-02-01');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CSP_LEVEL', 'CSP_LEVEL', '资质等级', '2', '二级资质', '2018-02-01');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CSP_LEVEL', 'CSP_LEVEL', '资质等级', '3', '三级资质', '2018-02-01');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CSP_LEVEL', 'CSP_LEVEL', '资质等级', '4', '三级暂定', '2018-02-01');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('IS_FLAG', 'IS_FLAG', '是否状态', '01', '是', '20170515');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('IS_FLAG', 'IS_FLAG', '是否状态', '02', '否', '20170515');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SECTTYPE', 'SECTTYPE', '物业类型', '01', '住宅', '2018-02-06');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SECTTYPE', 'SECTTYPE', '物业类型', '02', '非住宅', '2018-02-06');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SECTTYPESUB1', 'SECTTYPESUB1', '物业类型子项', '01', '多层住宅', '2018-02-06');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SECTTYPESUB1', 'SECTTYPESUB1', '物业类型子项', '02', '高层住宅', '2018-02-06');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SECTTYPESUB1', 'SECTTYPESUB1', '物业类型子项', '03', '联体别墅', '2018-02-06');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SECTTYPESUB1', 'SECTTYPESUB1', '物业类型子项', '04', '单体别墅', '2018-02-06');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SECTTYPESUB2', 'SECTTYPESUB2', '物业类型子项', '05', '商业用房', '2018-02-06');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SECTTYPESUB2', 'SECTTYPESUB2', '物业类型子项', '06', '工业厂房', '2018-02-06');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SECTTYPESUB2', 'SECTTYPESUB2', '物业类型子项', '07', '写字楼', '2018-02-06');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SECTTYPESUB2', 'SECTTYPESUB2', '物业类型子项', '08', '其他', '2018-02-06');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('USER_STATUS', 'USER_STATUS', '用户状态', '0', '正常使用', '2018-01-31');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('USER_STATUS', 'USER_STATUS', '用户状态', '2', '禁用', '2018-01-31');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('USER_STATUS', 'USER_STATUS', '用户状态', '3', '已注销', '2018-01-31');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('APP_TYPE', 'APP_TYPE', '流程类型', 'SECTADDFLOW', '项目信息采集流程', '2018-02-07');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('APP_TYPE', 'APP_TYPE', '流程类型', 'LEAVE_PROCESS', '部门请假流程', '20180105');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_STATUS', 'ORG_STATUS', '机构状态', '0', '正常使用', '2018-01-31');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_STATUS', 'ORG_STATUS', '机构状态', '1', '禁用', '2018-01-31');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('ORG_STATUS', 'ORG_STATUS', '机构状态', '2', '已注销', '2018-01-31');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EDUCATION', 'EDUCATION', '文化程度', '1', '初中', '2018-02-07');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EDUCATION', 'EDUCATION', '文化程度', '2', '高中', '2018-02-07');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EDUCATION', 'EDUCATION', '文化程度', '3', '大专', '2018-02-07');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EDUCATION', 'EDUCATION', '文化程度', '4', '本科', '2018-02-07');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EDUCATION', 'EDUCATION', '文化程度', '5', '硕士研究生', '2018-02-07');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('EDUCATION', 'EDUCATION', '文化程度', '6', '博士研究生', '2018-02-07');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SEXTYPE', 'SEXTYPE', '性别', '1', '男', '2018-02-07');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('SEXTYPE', 'SEXTYPE', '性别', '2', '女', '2018-02-07');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CERTTYPE', 'CERTTYPE', '证件类型', '1', '身份证', '2018-02-07');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('USER_TYPE', 'USER_TYPE', '人员类型', '01', '项目经理', '2018-02-09');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('NORM_STATUS', 'NORM_STATUS', '指标状态', '0', '待启用', '2018-02-27');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('NORM_STATUS', 'NORM_STATUS', '指标状态', '1', '正常', '2018-02-27');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('NORM_STATUS', 'NORM_STATUS', '指标状态', '2', '已注销', '2018-02-27');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('APP_TYPE', 'APP_TYPE', '流程类型', 'SECTDELEFLOW', '项目信息删除流程', '2018-02-28');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditQuotaObject', 'CreditQuotaObject', '诚信指标适用主体类型', '01', '物业公司', '2018-03-09');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditQuotaObject', 'CreditQuotaObject', '诚信指标适用主体类型', '02', '项目经理', '2018-03-09');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditQuotaObject', 'CreditQuotaObject', '诚信指标适用主体类型', '03', '物业公司和项目经理', '2018-03-09');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditInfoFrom', 'CreditInfoFrom', '不良信息来源', '01', '违法违规', '2018-03-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditInfoFrom', 'CreditInfoFrom', '不良信息来源', '02', '日常巡查及监督检查', '2018-03-14');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditInfoFrom', 'CreditInfoFrom', '不良信息来源', '03', '投诉信访', '2018-03-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('CreditInfoFrom', 'CreditInfoFrom', '不良信息来源', '04', '媒体曝光', '2018-03-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('PRODUCT_TYPE', 'PRODUCT_TYPE', '产品类型', '02', '数据平台', '2018-11-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('PRODUCT_TYPE', 'PRODUCT_TYPE', '产品类型', '03', '房维', '2018-11-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('PRODUCT_TYPE', 'PRODUCT_TYPE', '产品类型', '04', '其他', '2018-11-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('TRADE_CODE', 'TRADE_CODE', '行业代码', '00', '行业代码', '2018-11-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('TRADE_CODE', 'TRADE_CODE', '行业代码', '01', '行业代码2', '2018-11-12');
INSERT INTO "VOTE"."CODE_DATA" VALUES ('REGIONAL_MARKET', 'REGIONAL_MARKET', '地区市场', '00', '中国', '2018-11-12');

-- ----------------------------
-- Indexes structure for table CODE_DATA
-- ----------------------------

-- ----------------------------
-- Checks structure for table CODE_DATA
-- ----------------------------
ALTER TABLE "VOTE"."CODE_DATA" ADD CHECK ("CODE_NO" IS NOT NULL);
ALTER TABLE "VOTE"."CODE_DATA" ADD CHECK ("CODE_KEY" IS NOT NULL);
ALTER TABLE "VOTE"."CODE_DATA" ADD CHECK ("CODE_NO" IS NOT NULL);
ALTER TABLE "VOTE"."CODE_DATA" ADD CHECK ("CODE_KEY" IS NOT NULL);
ALTER TABLE "VOTE"."CODE_DATA" ADD CHECK ("CODE_NO" IS NOT NULL);
ALTER TABLE "VOTE"."CODE_DATA" ADD CHECK ("CODE_KEY" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CODE_DATA
-- ----------------------------
ALTER TABLE "VOTE"."CODE_DATA" ADD PRIMARY KEY ("CODE_NO", "CODE_KEY");
