package com.indihx.elecvote.dao;

import com.indihx.elecvote.entity.VoteWorkspace;
import com.indihx.elecvote.entity.VoteWorkspaceExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteWorkspaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    long countByExample(VoteWorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int deleteByExample(VoteWorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal wsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int insert(VoteWorkspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int insertSelective(VoteWorkspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    List<VoteWorkspace> selectByExample(VoteWorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    VoteWorkspace selectByPrimaryKey(BigDecimal wsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") VoteWorkspace record, @Param("example") VoteWorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByExample(@Param("record") VoteWorkspace record, @Param("example") VoteWorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByPrimaryKeySelective(VoteWorkspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_WORKSPACE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByPrimaryKey(VoteWorkspace record);
}