package com.indihx.elecvote.dao;

import com.indihx.elecvote.entity.VoteHouseInfo;
import com.indihx.elecvote.entity.VoteHouseInfoExample;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface VoteHouseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    long countByExample(VoteHouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int deleteByExample(VoteHouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int insert(VoteHouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int insertSelective(VoteHouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    List<VoteHouseInfo> selectByExample(VoteHouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    VoteHouseInfo selectByPrimaryKey(BigDecimal infoId);
   // List<VoteHouseInfo> selectUnlinkHouse(@Param("sectName") String sectName, @Param("buildCode") String buildCode,
    		//@Param("unitCode") String unitCode,@Param("floorCode") String floorCode,@Param("roomCode") String roomCode,@Param("topicId") String topicId)
    //查询没有关联投票的房屋信息
    List<VoteHouseInfo> selectUnlinkHouse(Map<String, Object> map);
    //查询已经关联的房屋信息
    List<VoteHouseInfo> selectLinkHouse(Map<String, Object> map);
    //根据小区名查询楼栋号
    List<VoteHouseInfo> selectDistinctBuild(VoteHouseInfoExample example);
    //查询单元号
    List<VoteHouseInfo> selectDistinctUnit(VoteHouseInfoExample example);
    //查询楼层号
    List<VoteHouseInfo> selectDistinctFloor(VoteHouseInfoExample example);
    //查询房间号
    List<VoteHouseInfo> selectDistinctRoom(VoteHouseInfoExample example);

    //根据openid查询房屋信息
    List<VoteHouseInfo> selectByOpenId(@Param("userId")String userId);
    
    //查询某一个议题下还没有投票的分户
    List<VoteHouseInfo> selectUnvoteByTopicId(Map<String, Object> map);
    /**
     * 
     */
    HashMap<String, BigDecimal> selectTotalBySectId(BigDecimal SectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") VoteHouseInfo record, @Param("example") VoteHouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByExample(@Param("record") VoteHouseInfo record, @Param("example") VoteHouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByPrimaryKeySelective(VoteHouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByPrimaryKey(VoteHouseInfo record);
}