package com.indihx.elecvote.dao;

import com.indihx.elecvote.entity.VoteTopicInfo;
import com.indihx.elecvote.entity.VoteTopicInfoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteTopicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    long countByExample(VoteTopicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int deleteByExample(VoteTopicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int insert(VoteTopicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int insertSelective(VoteTopicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    List<VoteTopicInfo> selectByExample(VoteTopicInfoExample example);
    //查询某个用户所有没有投票的议题
    List<VoteTopicInfo> selectUnvotedByOpenId(@Param("openId") String openId);
    //查询某个用户所有已经投过票的议题
    List<VoteTopicInfo> selectVotedByOpenId(@Param("openId") String openId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    VoteTopicInfo selectByPrimaryKey(BigDecimal topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") VoteTopicInfo record, @Param("example") VoteTopicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByExample(@Param("record") VoteTopicInfo record, @Param("example") VoteTopicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByPrimaryKeySelective(VoteTopicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_TOPIC_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByPrimaryKey(VoteTopicInfo record);
}