package com.indihx.elecvote.dao;

import com.indihx.elecvote.entity.VoteResultInfo;
import com.indihx.elecvote.entity.VoteResultInfoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteResultInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    long countByExample(VoteResultInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int deleteByExample(VoteResultInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal resultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int insert(VoteResultInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int insertSelective(VoteResultInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    List<VoteResultInfo> selectByExample(VoteResultInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    VoteResultInfo selectByPrimaryKey(BigDecimal resultId);
    
    BigDecimal selectSumArea(@Param("topicId") String topicId, @Param("voteResult") String voteResult);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") VoteResultInfo record, @Param("example") VoteResultInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByExample(@Param("record") VoteResultInfo record, @Param("example") VoteResultInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByPrimaryKeySelective(VoteResultInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByPrimaryKey(VoteResultInfo record);
}