package com.indihx.elecvote.dao;

import com.indihx.elecvote.entity.VoteResultSum;
import com.indihx.elecvote.entity.VoteResultSumExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteResultSumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    long countByExample(VoteResultSumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int deleteByExample(VoteResultSumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int insert(VoteResultSum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int insertSelective(VoteResultSum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    List<VoteResultSum> selectByExample(VoteResultSumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    VoteResultSum selectByPrimaryKey(BigDecimal topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") VoteResultSum record, @Param("example") VoteResultSumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByExample(@Param("record") VoteResultSum record, @Param("example") VoteResultSumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByPrimaryKeySelective(VoteResultSum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    int updateByPrimaryKey(VoteResultSum record);
}