package com.indihx.elecvote.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class VoteResultSumExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public VoteResultSumExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTopicIdIsNull() {
            addCriterion("TOPIC_ID is null");
            return (Criteria) this;
        }

        public Criteria andTopicIdIsNotNull() {
            addCriterion("TOPIC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTopicIdEqualTo(BigDecimal value) {
            addCriterion("TOPIC_ID =", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotEqualTo(BigDecimal value) {
            addCriterion("TOPIC_ID <>", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdGreaterThan(BigDecimal value) {
            addCriterion("TOPIC_ID >", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOPIC_ID >=", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdLessThan(BigDecimal value) {
            addCriterion("TOPIC_ID <", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOPIC_ID <=", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdIn(List<BigDecimal> values) {
            addCriterion("TOPIC_ID in", values, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotIn(List<BigDecimal> values) {
            addCriterion("TOPIC_ID not in", values, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOPIC_ID between", value1, value2, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOPIC_ID not between", value1, value2, "topicId");
            return (Criteria) this;
        }

        public Criteria andSumCountIsNull() {
            addCriterion("SUM_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andSumCountIsNotNull() {
            addCriterion("SUM_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSumCountEqualTo(Long value) {
            addCriterion("SUM_COUNT =", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountNotEqualTo(Long value) {
            addCriterion("SUM_COUNT <>", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountGreaterThan(Long value) {
            addCriterion("SUM_COUNT >", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountGreaterThanOrEqualTo(Long value) {
            addCriterion("SUM_COUNT >=", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountLessThan(Long value) {
            addCriterion("SUM_COUNT <", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountLessThanOrEqualTo(Long value) {
            addCriterion("SUM_COUNT <=", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountIn(List<Long> values) {
            addCriterion("SUM_COUNT in", values, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountNotIn(List<Long> values) {
            addCriterion("SUM_COUNT not in", values, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountBetween(Long value1, Long value2) {
            addCriterion("SUM_COUNT between", value1, value2, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountNotBetween(Long value1, Long value2) {
            addCriterion("SUM_COUNT not between", value1, value2, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumAreaIsNull() {
            addCriterion("SUM_AREA is null");
            return (Criteria) this;
        }

        public Criteria andSumAreaIsNotNull() {
            addCriterion("SUM_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andSumAreaEqualTo(BigDecimal value) {
            addCriterion("SUM_AREA =", value, "sumArea");
            return (Criteria) this;
        }

        public Criteria andSumAreaNotEqualTo(BigDecimal value) {
            addCriterion("SUM_AREA <>", value, "sumArea");
            return (Criteria) this;
        }

        public Criteria andSumAreaGreaterThan(BigDecimal value) {
            addCriterion("SUM_AREA >", value, "sumArea");
            return (Criteria) this;
        }

        public Criteria andSumAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_AREA >=", value, "sumArea");
            return (Criteria) this;
        }

        public Criteria andSumAreaLessThan(BigDecimal value) {
            addCriterion("SUM_AREA <", value, "sumArea");
            return (Criteria) this;
        }

        public Criteria andSumAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_AREA <=", value, "sumArea");
            return (Criteria) this;
        }

        public Criteria andSumAreaIn(List<BigDecimal> values) {
            addCriterion("SUM_AREA in", values, "sumArea");
            return (Criteria) this;
        }

        public Criteria andSumAreaNotIn(List<BigDecimal> values) {
            addCriterion("SUM_AREA not in", values, "sumArea");
            return (Criteria) this;
        }

        public Criteria andSumAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_AREA between", value1, value2, "sumArea");
            return (Criteria) this;
        }

        public Criteria andSumAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_AREA not between", value1, value2, "sumArea");
            return (Criteria) this;
        }

        public Criteria andAgreeHouIsNull() {
            addCriterion("AGREE_HOU is null");
            return (Criteria) this;
        }

        public Criteria andAgreeHouIsNotNull() {
            addCriterion("AGREE_HOU is not null");
            return (Criteria) this;
        }

        public Criteria andAgreeHouEqualTo(Long value) {
            addCriterion("AGREE_HOU =", value, "agreeHou");
            return (Criteria) this;
        }

        public Criteria andAgreeHouNotEqualTo(Long value) {
            addCriterion("AGREE_HOU <>", value, "agreeHou");
            return (Criteria) this;
        }

        public Criteria andAgreeHouGreaterThan(Long value) {
            addCriterion("AGREE_HOU >", value, "agreeHou");
            return (Criteria) this;
        }

        public Criteria andAgreeHouGreaterThanOrEqualTo(Long value) {
            addCriterion("AGREE_HOU >=", value, "agreeHou");
            return (Criteria) this;
        }

        public Criteria andAgreeHouLessThan(Long value) {
            addCriterion("AGREE_HOU <", value, "agreeHou");
            return (Criteria) this;
        }

        public Criteria andAgreeHouLessThanOrEqualTo(Long value) {
            addCriterion("AGREE_HOU <=", value, "agreeHou");
            return (Criteria) this;
        }

        public Criteria andAgreeHouIn(List<Long> values) {
            addCriterion("AGREE_HOU in", values, "agreeHou");
            return (Criteria) this;
        }

        public Criteria andAgreeHouNotIn(List<Long> values) {
            addCriterion("AGREE_HOU not in", values, "agreeHou");
            return (Criteria) this;
        }

        public Criteria andAgreeHouBetween(Long value1, Long value2) {
            addCriterion("AGREE_HOU between", value1, value2, "agreeHou");
            return (Criteria) this;
        }

        public Criteria andAgreeHouNotBetween(Long value1, Long value2) {
            addCriterion("AGREE_HOU not between", value1, value2, "agreeHou");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateIsNull() {
            addCriterion("AGREE_HOU_RATE is null");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateIsNotNull() {
            addCriterion("AGREE_HOU_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateEqualTo(BigDecimal value) {
            addCriterion("AGREE_HOU_RATE =", value, "agreeHouRate");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateNotEqualTo(BigDecimal value) {
            addCriterion("AGREE_HOU_RATE <>", value, "agreeHouRate");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateGreaterThan(BigDecimal value) {
            addCriterion("AGREE_HOU_RATE >", value, "agreeHouRate");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AGREE_HOU_RATE >=", value, "agreeHouRate");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateLessThan(BigDecimal value) {
            addCriterion("AGREE_HOU_RATE <", value, "agreeHouRate");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AGREE_HOU_RATE <=", value, "agreeHouRate");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateIn(List<BigDecimal> values) {
            addCriterion("AGREE_HOU_RATE in", values, "agreeHouRate");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateNotIn(List<BigDecimal> values) {
            addCriterion("AGREE_HOU_RATE not in", values, "agreeHouRate");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGREE_HOU_RATE between", value1, value2, "agreeHouRate");
            return (Criteria) this;
        }

        public Criteria andAgreeHouRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGREE_HOU_RATE not between", value1, value2, "agreeHouRate");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaIsNull() {
            addCriterion("AGREE_AREA is null");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaIsNotNull() {
            addCriterion("AGREE_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaEqualTo(BigDecimal value) {
            addCriterion("AGREE_AREA =", value, "agreeArea");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaNotEqualTo(BigDecimal value) {
            addCriterion("AGREE_AREA <>", value, "agreeArea");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaGreaterThan(BigDecimal value) {
            addCriterion("AGREE_AREA >", value, "agreeArea");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AGREE_AREA >=", value, "agreeArea");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaLessThan(BigDecimal value) {
            addCriterion("AGREE_AREA <", value, "agreeArea");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AGREE_AREA <=", value, "agreeArea");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaIn(List<BigDecimal> values) {
            addCriterion("AGREE_AREA in", values, "agreeArea");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaNotIn(List<BigDecimal> values) {
            addCriterion("AGREE_AREA not in", values, "agreeArea");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGREE_AREA between", value1, value2, "agreeArea");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGREE_AREA not between", value1, value2, "agreeArea");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateIsNull() {
            addCriterion("AGREE_AREA_RATE is null");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateIsNotNull() {
            addCriterion("AGREE_AREA_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateEqualTo(BigDecimal value) {
            addCriterion("AGREE_AREA_RATE =", value, "agreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateNotEqualTo(BigDecimal value) {
            addCriterion("AGREE_AREA_RATE <>", value, "agreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateGreaterThan(BigDecimal value) {
            addCriterion("AGREE_AREA_RATE >", value, "agreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AGREE_AREA_RATE >=", value, "agreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateLessThan(BigDecimal value) {
            addCriterion("AGREE_AREA_RATE <", value, "agreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AGREE_AREA_RATE <=", value, "agreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateIn(List<BigDecimal> values) {
            addCriterion("AGREE_AREA_RATE in", values, "agreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateNotIn(List<BigDecimal> values) {
            addCriterion("AGREE_AREA_RATE not in", values, "agreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGREE_AREA_RATE between", value1, value2, "agreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andAgreeAreaRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGREE_AREA_RATE not between", value1, value2, "agreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouIsNull() {
            addCriterion("UNAGREE_HOU is null");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouIsNotNull() {
            addCriterion("UNAGREE_HOU is not null");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouEqualTo(Long value) {
            addCriterion("UNAGREE_HOU =", value, "unagreeHou");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouNotEqualTo(Long value) {
            addCriterion("UNAGREE_HOU <>", value, "unagreeHou");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouGreaterThan(Long value) {
            addCriterion("UNAGREE_HOU >", value, "unagreeHou");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouGreaterThanOrEqualTo(Long value) {
            addCriterion("UNAGREE_HOU >=", value, "unagreeHou");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouLessThan(Long value) {
            addCriterion("UNAGREE_HOU <", value, "unagreeHou");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouLessThanOrEqualTo(Long value) {
            addCriterion("UNAGREE_HOU <=", value, "unagreeHou");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouIn(List<Long> values) {
            addCriterion("UNAGREE_HOU in", values, "unagreeHou");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouNotIn(List<Long> values) {
            addCriterion("UNAGREE_HOU not in", values, "unagreeHou");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouBetween(Long value1, Long value2) {
            addCriterion("UNAGREE_HOU between", value1, value2, "unagreeHou");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouNotBetween(Long value1, Long value2) {
            addCriterion("UNAGREE_HOU not between", value1, value2, "unagreeHou");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateIsNull() {
            addCriterion("UNAGREE_HOU_RATE is null");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateIsNotNull() {
            addCriterion("UNAGREE_HOU_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_HOU_RATE =", value, "unagreeHouRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateNotEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_HOU_RATE <>", value, "unagreeHouRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateGreaterThan(BigDecimal value) {
            addCriterion("UNAGREE_HOU_RATE >", value, "unagreeHouRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_HOU_RATE >=", value, "unagreeHouRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateLessThan(BigDecimal value) {
            addCriterion("UNAGREE_HOU_RATE <", value, "unagreeHouRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_HOU_RATE <=", value, "unagreeHouRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateIn(List<BigDecimal> values) {
            addCriterion("UNAGREE_HOU_RATE in", values, "unagreeHouRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateNotIn(List<BigDecimal> values) {
            addCriterion("UNAGREE_HOU_RATE not in", values, "unagreeHouRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNAGREE_HOU_RATE between", value1, value2, "unagreeHouRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeHouRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNAGREE_HOU_RATE not between", value1, value2, "unagreeHouRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaIsNull() {
            addCriterion("UNAGREE_AREA is null");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaIsNotNull() {
            addCriterion("UNAGREE_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_AREA =", value, "unagreeArea");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaNotEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_AREA <>", value, "unagreeArea");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaGreaterThan(BigDecimal value) {
            addCriterion("UNAGREE_AREA >", value, "unagreeArea");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_AREA >=", value, "unagreeArea");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaLessThan(BigDecimal value) {
            addCriterion("UNAGREE_AREA <", value, "unagreeArea");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_AREA <=", value, "unagreeArea");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaIn(List<BigDecimal> values) {
            addCriterion("UNAGREE_AREA in", values, "unagreeArea");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaNotIn(List<BigDecimal> values) {
            addCriterion("UNAGREE_AREA not in", values, "unagreeArea");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNAGREE_AREA between", value1, value2, "unagreeArea");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNAGREE_AREA not between", value1, value2, "unagreeArea");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateIsNull() {
            addCriterion("UNAGREE_AREA_RATE is null");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateIsNotNull() {
            addCriterion("UNAGREE_AREA_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_AREA_RATE =", value, "unagreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateNotEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_AREA_RATE <>", value, "unagreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateGreaterThan(BigDecimal value) {
            addCriterion("UNAGREE_AREA_RATE >", value, "unagreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_AREA_RATE >=", value, "unagreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateLessThan(BigDecimal value) {
            addCriterion("UNAGREE_AREA_RATE <", value, "unagreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UNAGREE_AREA_RATE <=", value, "unagreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateIn(List<BigDecimal> values) {
            addCriterion("UNAGREE_AREA_RATE in", values, "unagreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateNotIn(List<BigDecimal> values) {
            addCriterion("UNAGREE_AREA_RATE not in", values, "unagreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNAGREE_AREA_RATE between", value1, value2, "unagreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andUnagreeAreaRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNAGREE_AREA_RATE not between", value1, value2, "unagreeAreaRate");
            return (Criteria) this;
        }

        public Criteria andQuitHouIsNull() {
            addCriterion("QUIT_HOU is null");
            return (Criteria) this;
        }

        public Criteria andQuitHouIsNotNull() {
            addCriterion("QUIT_HOU is not null");
            return (Criteria) this;
        }

        public Criteria andQuitHouEqualTo(Long value) {
            addCriterion("QUIT_HOU =", value, "quitHou");
            return (Criteria) this;
        }

        public Criteria andQuitHouNotEqualTo(Long value) {
            addCriterion("QUIT_HOU <>", value, "quitHou");
            return (Criteria) this;
        }

        public Criteria andQuitHouGreaterThan(Long value) {
            addCriterion("QUIT_HOU >", value, "quitHou");
            return (Criteria) this;
        }

        public Criteria andQuitHouGreaterThanOrEqualTo(Long value) {
            addCriterion("QUIT_HOU >=", value, "quitHou");
            return (Criteria) this;
        }

        public Criteria andQuitHouLessThan(Long value) {
            addCriterion("QUIT_HOU <", value, "quitHou");
            return (Criteria) this;
        }

        public Criteria andQuitHouLessThanOrEqualTo(Long value) {
            addCriterion("QUIT_HOU <=", value, "quitHou");
            return (Criteria) this;
        }

        public Criteria andQuitHouIn(List<Long> values) {
            addCriterion("QUIT_HOU in", values, "quitHou");
            return (Criteria) this;
        }

        public Criteria andQuitHouNotIn(List<Long> values) {
            addCriterion("QUIT_HOU not in", values, "quitHou");
            return (Criteria) this;
        }

        public Criteria andQuitHouBetween(Long value1, Long value2) {
            addCriterion("QUIT_HOU between", value1, value2, "quitHou");
            return (Criteria) this;
        }

        public Criteria andQuitHouNotBetween(Long value1, Long value2) {
            addCriterion("QUIT_HOU not between", value1, value2, "quitHou");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateIsNull() {
            addCriterion("QUIT_HOU_RATE is null");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateIsNotNull() {
            addCriterion("QUIT_HOU_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateEqualTo(BigDecimal value) {
            addCriterion("QUIT_HOU_RATE =", value, "quitHouRate");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateNotEqualTo(BigDecimal value) {
            addCriterion("QUIT_HOU_RATE <>", value, "quitHouRate");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateGreaterThan(BigDecimal value) {
            addCriterion("QUIT_HOU_RATE >", value, "quitHouRate");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("QUIT_HOU_RATE >=", value, "quitHouRate");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateLessThan(BigDecimal value) {
            addCriterion("QUIT_HOU_RATE <", value, "quitHouRate");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("QUIT_HOU_RATE <=", value, "quitHouRate");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateIn(List<BigDecimal> values) {
            addCriterion("QUIT_HOU_RATE in", values, "quitHouRate");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateNotIn(List<BigDecimal> values) {
            addCriterion("QUIT_HOU_RATE not in", values, "quitHouRate");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUIT_HOU_RATE between", value1, value2, "quitHouRate");
            return (Criteria) this;
        }

        public Criteria andQuitHouRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUIT_HOU_RATE not between", value1, value2, "quitHouRate");
            return (Criteria) this;
        }

        public Criteria andQuitAreaIsNull() {
            addCriterion("QUIT_AREA is null");
            return (Criteria) this;
        }

        public Criteria andQuitAreaIsNotNull() {
            addCriterion("QUIT_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andQuitAreaEqualTo(BigDecimal value) {
            addCriterion("QUIT_AREA =", value, "quitArea");
            return (Criteria) this;
        }

        public Criteria andQuitAreaNotEqualTo(BigDecimal value) {
            addCriterion("QUIT_AREA <>", value, "quitArea");
            return (Criteria) this;
        }

        public Criteria andQuitAreaGreaterThan(BigDecimal value) {
            addCriterion("QUIT_AREA >", value, "quitArea");
            return (Criteria) this;
        }

        public Criteria andQuitAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("QUIT_AREA >=", value, "quitArea");
            return (Criteria) this;
        }

        public Criteria andQuitAreaLessThan(BigDecimal value) {
            addCriterion("QUIT_AREA <", value, "quitArea");
            return (Criteria) this;
        }

        public Criteria andQuitAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("QUIT_AREA <=", value, "quitArea");
            return (Criteria) this;
        }

        public Criteria andQuitAreaIn(List<BigDecimal> values) {
            addCriterion("QUIT_AREA in", values, "quitArea");
            return (Criteria) this;
        }

        public Criteria andQuitAreaNotIn(List<BigDecimal> values) {
            addCriterion("QUIT_AREA not in", values, "quitArea");
            return (Criteria) this;
        }

        public Criteria andQuitAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUIT_AREA between", value1, value2, "quitArea");
            return (Criteria) this;
        }

        public Criteria andQuitAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUIT_AREA not between", value1, value2, "quitArea");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateIsNull() {
            addCriterion("QUIT_AREA_RATE is null");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateIsNotNull() {
            addCriterion("QUIT_AREA_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateEqualTo(BigDecimal value) {
            addCriterion("QUIT_AREA_RATE =", value, "quitAreaRate");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateNotEqualTo(BigDecimal value) {
            addCriterion("QUIT_AREA_RATE <>", value, "quitAreaRate");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateGreaterThan(BigDecimal value) {
            addCriterion("QUIT_AREA_RATE >", value, "quitAreaRate");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("QUIT_AREA_RATE >=", value, "quitAreaRate");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateLessThan(BigDecimal value) {
            addCriterion("QUIT_AREA_RATE <", value, "quitAreaRate");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("QUIT_AREA_RATE <=", value, "quitAreaRate");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateIn(List<BigDecimal> values) {
            addCriterion("QUIT_AREA_RATE in", values, "quitAreaRate");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateNotIn(List<BigDecimal> values) {
            addCriterion("QUIT_AREA_RATE not in", values, "quitAreaRate");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUIT_AREA_RATE between", value1, value2, "quitAreaRate");
            return (Criteria) this;
        }

        public Criteria andQuitAreaRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUIT_AREA_RATE not between", value1, value2, "quitAreaRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouIsNull() {
            addCriterion("NONVOTE_HOU is null");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouIsNotNull() {
            addCriterion("NONVOTE_HOU is not null");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouEqualTo(Long value) {
            addCriterion("NONVOTE_HOU =", value, "nonvoteHou");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouNotEqualTo(Long value) {
            addCriterion("NONVOTE_HOU <>", value, "nonvoteHou");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouGreaterThan(Long value) {
            addCriterion("NONVOTE_HOU >", value, "nonvoteHou");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouGreaterThanOrEqualTo(Long value) {
            addCriterion("NONVOTE_HOU >=", value, "nonvoteHou");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouLessThan(Long value) {
            addCriterion("NONVOTE_HOU <", value, "nonvoteHou");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouLessThanOrEqualTo(Long value) {
            addCriterion("NONVOTE_HOU <=", value, "nonvoteHou");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouIn(List<Long> values) {
            addCriterion("NONVOTE_HOU in", values, "nonvoteHou");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouNotIn(List<Long> values) {
            addCriterion("NONVOTE_HOU not in", values, "nonvoteHou");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouBetween(Long value1, Long value2) {
            addCriterion("NONVOTE_HOU between", value1, value2, "nonvoteHou");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouNotBetween(Long value1, Long value2) {
            addCriterion("NONVOTE_HOU not between", value1, value2, "nonvoteHou");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateIsNull() {
            addCriterion("NONVOTE_HOU_RATE is null");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateIsNotNull() {
            addCriterion("NONVOTE_HOU_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_HOU_RATE =", value, "nonvoteHouRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateNotEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_HOU_RATE <>", value, "nonvoteHouRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateGreaterThan(BigDecimal value) {
            addCriterion("NONVOTE_HOU_RATE >", value, "nonvoteHouRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_HOU_RATE >=", value, "nonvoteHouRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateLessThan(BigDecimal value) {
            addCriterion("NONVOTE_HOU_RATE <", value, "nonvoteHouRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_HOU_RATE <=", value, "nonvoteHouRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateIn(List<BigDecimal> values) {
            addCriterion("NONVOTE_HOU_RATE in", values, "nonvoteHouRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateNotIn(List<BigDecimal> values) {
            addCriterion("NONVOTE_HOU_RATE not in", values, "nonvoteHouRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NONVOTE_HOU_RATE between", value1, value2, "nonvoteHouRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteHouRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NONVOTE_HOU_RATE not between", value1, value2, "nonvoteHouRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaIsNull() {
            addCriterion("NONVOTE_AREA is null");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaIsNotNull() {
            addCriterion("NONVOTE_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_AREA =", value, "nonvoteArea");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaNotEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_AREA <>", value, "nonvoteArea");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaGreaterThan(BigDecimal value) {
            addCriterion("NONVOTE_AREA >", value, "nonvoteArea");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_AREA >=", value, "nonvoteArea");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaLessThan(BigDecimal value) {
            addCriterion("NONVOTE_AREA <", value, "nonvoteArea");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_AREA <=", value, "nonvoteArea");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaIn(List<BigDecimal> values) {
            addCriterion("NONVOTE_AREA in", values, "nonvoteArea");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaNotIn(List<BigDecimal> values) {
            addCriterion("NONVOTE_AREA not in", values, "nonvoteArea");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NONVOTE_AREA between", value1, value2, "nonvoteArea");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NONVOTE_AREA not between", value1, value2, "nonvoteArea");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateIsNull() {
            addCriterion("NONVOTE_AREA_RATE is null");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateIsNotNull() {
            addCriterion("NONVOTE_AREA_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_AREA_RATE =", value, "nonvoteAreaRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateNotEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_AREA_RATE <>", value, "nonvoteAreaRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateGreaterThan(BigDecimal value) {
            addCriterion("NONVOTE_AREA_RATE >", value, "nonvoteAreaRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_AREA_RATE >=", value, "nonvoteAreaRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateLessThan(BigDecimal value) {
            addCriterion("NONVOTE_AREA_RATE <", value, "nonvoteAreaRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NONVOTE_AREA_RATE <=", value, "nonvoteAreaRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateIn(List<BigDecimal> values) {
            addCriterion("NONVOTE_AREA_RATE in", values, "nonvoteAreaRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateNotIn(List<BigDecimal> values) {
            addCriterion("NONVOTE_AREA_RATE not in", values, "nonvoteAreaRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NONVOTE_AREA_RATE between", value1, value2, "nonvoteAreaRate");
            return (Criteria) this;
        }

        public Criteria andNonvoteAreaRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NONVOTE_AREA_RATE not between", value1, value2, "nonvoteAreaRate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 12 18:41:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_RESULT_SUM
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}