package com.indihx.elecvote.entity;

import java.math.BigDecimal;

public class VoteWorkspace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.WS_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal wsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.SECT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal sectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.WS_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String wsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.TOTAL_AMT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal totalAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.REPAIR_CONTENT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String repairContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.REPAIR_REASON
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String repairReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.OLD_WS_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String oldWsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.HOU_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal houCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.SUM_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal sumArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.WS_STAGE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String wsStage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_WORKSPACE.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.WS_ID
     *
     * @return the value of VOTE_WORKSPACE.WS_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getWsId() {
        return wsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.WS_ID
     *
     * @param wsId the value for VOTE_WORKSPACE.WS_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setWsId(BigDecimal wsId) {
        this.wsId = wsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.SECT_ID
     *
     * @return the value of VOTE_WORKSPACE.SECT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getSectId() {
        return sectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.SECT_ID
     *
     * @param sectId the value for VOTE_WORKSPACE.SECT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setSectId(BigDecimal sectId) {
        this.sectId = sectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.WS_NAME
     *
     * @return the value of VOTE_WORKSPACE.WS_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getWsName() {
        return wsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.WS_NAME
     *
     * @param wsName the value for VOTE_WORKSPACE.WS_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setWsName(String wsName) {
        this.wsName = wsName == null ? null : wsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.TOTAL_AMT
     *
     * @return the value of VOTE_WORKSPACE.TOTAL_AMT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.TOTAL_AMT
     *
     * @param totalAmt the value for VOTE_WORKSPACE.TOTAL_AMT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setTotalAmt(BigDecimal totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.REPAIR_CONTENT
     *
     * @return the value of VOTE_WORKSPACE.REPAIR_CONTENT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getRepairContent() {
        return repairContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.REPAIR_CONTENT
     *
     * @param repairContent the value for VOTE_WORKSPACE.REPAIR_CONTENT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setRepairContent(String repairContent) {
        this.repairContent = repairContent == null ? null : repairContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.REPAIR_REASON
     *
     * @return the value of VOTE_WORKSPACE.REPAIR_REASON
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getRepairReason() {
        return repairReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.REPAIR_REASON
     *
     * @param repairReason the value for VOTE_WORKSPACE.REPAIR_REASON
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setRepairReason(String repairReason) {
        this.repairReason = repairReason == null ? null : repairReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.OLD_WS_ID
     *
     * @return the value of VOTE_WORKSPACE.OLD_WS_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getOldWsId() {
        return oldWsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.OLD_WS_ID
     *
     * @param oldWsId the value for VOTE_WORKSPACE.OLD_WS_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setOldWsId(String oldWsId) {
        this.oldWsId = oldWsId == null ? null : oldWsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.HOU_COUNT
     *
     * @return the value of VOTE_WORKSPACE.HOU_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getHouCount() {
        return houCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.HOU_COUNT
     *
     * @param houCount the value for VOTE_WORKSPACE.HOU_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setHouCount(BigDecimal houCount) {
        this.houCount = houCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.SUM_AREA
     *
     * @return the value of VOTE_WORKSPACE.SUM_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getSumArea() {
        return sumArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.SUM_AREA
     *
     * @param sumArea the value for VOTE_WORKSPACE.SUM_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setSumArea(BigDecimal sumArea) {
        this.sumArea = sumArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.WS_STAGE
     *
     * @return the value of VOTE_WORKSPACE.WS_STAGE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getWsStage() {
        return wsStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.WS_STAGE
     *
     * @param wsStage the value for VOTE_WORKSPACE.WS_STAGE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setWsStage(String wsStage) {
        this.wsStage = wsStage == null ? null : wsStage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.CREATE_DATE
     *
     * @return the value of VOTE_WORKSPACE.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.CREATE_DATE
     *
     * @param createDate the value for VOTE_WORKSPACE.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.CREATE_TIME
     *
     * @return the value of VOTE_WORKSPACE.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.CREATE_TIME
     *
     * @param createTime the value for VOTE_WORKSPACE.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_WORKSPACE.REMARK
     *
     * @return the value of VOTE_WORKSPACE.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_WORKSPACE.REMARK
     *
     * @param remark the value for VOTE_WORKSPACE.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}