package com.indihx.elecvote.entity;

import java.math.BigDecimal;

public class VoteScopeInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SCOPE_INFO.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SCOPE_INFO.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal topicId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SCOPE_INFO.INFO_ID
     *
     * @return the value of VOTE_SCOPE_INFO.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SCOPE_INFO.INFO_ID
     *
     * @param infoId the value for VOTE_SCOPE_INFO.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setInfoId(BigDecimal infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SCOPE_INFO.TOPIC_ID
     *
     * @return the value of VOTE_SCOPE_INFO.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SCOPE_INFO.TOPIC_ID
     *
     * @param topicId the value for VOTE_SCOPE_INFO.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setTopicId(BigDecimal topicId) {
        this.topicId = topicId;
    }
}