package com.indihx.elecvote.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class VoteHouseInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public VoteHouseInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInfoIdIsNull() {
            addCriterion("INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNotNull() {
            addCriterion("INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIdEqualTo(BigDecimal value) {
            addCriterion("INFO_ID =", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotEqualTo(BigDecimal value) {
            addCriterion("INFO_ID <>", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThan(BigDecimal value) {
            addCriterion("INFO_ID >", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INFO_ID >=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThan(BigDecimal value) {
            addCriterion("INFO_ID <", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INFO_ID <=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdIn(List<BigDecimal> values) {
            addCriterion("INFO_ID in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotIn(List<BigDecimal> values) {
            addCriterion("INFO_ID not in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INFO_ID between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INFO_ID not between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoAddrIsNull() {
            addCriterion("INFO_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andInfoAddrIsNotNull() {
            addCriterion("INFO_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andInfoAddrEqualTo(String value) {
            addCriterion("INFO_ADDR =", value, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrNotEqualTo(String value) {
            addCriterion("INFO_ADDR <>", value, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrGreaterThan(String value) {
            addCriterion("INFO_ADDR >", value, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_ADDR >=", value, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrLessThan(String value) {
            addCriterion("INFO_ADDR <", value, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrLessThanOrEqualTo(String value) {
            addCriterion("INFO_ADDR <=", value, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrLike(String value) {
            addCriterion("INFO_ADDR like", value, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrNotLike(String value) {
            addCriterion("INFO_ADDR not like", value, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrIn(List<String> values) {
            addCriterion("INFO_ADDR in", values, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrNotIn(List<String> values) {
            addCriterion("INFO_ADDR not in", values, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrBetween(String value1, String value2) {
            addCriterion("INFO_ADDR between", value1, value2, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAddrNotBetween(String value1, String value2) {
            addCriterion("INFO_ADDR not between", value1, value2, "infoAddr");
            return (Criteria) this;
        }

        public Criteria andInfoAreaIsNull() {
            addCriterion("INFO_AREA is null");
            return (Criteria) this;
        }

        public Criteria andInfoAreaIsNotNull() {
            addCriterion("INFO_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andInfoAreaEqualTo(BigDecimal value) {
            addCriterion("INFO_AREA =", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaNotEqualTo(BigDecimal value) {
            addCriterion("INFO_AREA <>", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaGreaterThan(BigDecimal value) {
            addCriterion("INFO_AREA >", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INFO_AREA >=", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaLessThan(BigDecimal value) {
            addCriterion("INFO_AREA <", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INFO_AREA <=", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaIn(List<BigDecimal> values) {
            addCriterion("INFO_AREA in", values, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaNotIn(List<BigDecimal> values) {
            addCriterion("INFO_AREA not in", values, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INFO_AREA between", value1, value2, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INFO_AREA not between", value1, value2, "infoArea");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIsNull() {
            addCriterion("OWNER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIsNotNull() {
            addCriterion("OWNER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNameEqualTo(String value) {
            addCriterion("OWNER_NAME =", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotEqualTo(String value) {
            addCriterion("OWNER_NAME <>", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameGreaterThan(String value) {
            addCriterion("OWNER_NAME >", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER_NAME >=", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLessThan(String value) {
            addCriterion("OWNER_NAME <", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLessThanOrEqualTo(String value) {
            addCriterion("OWNER_NAME <=", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameLike(String value) {
            addCriterion("OWNER_NAME like", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotLike(String value) {
            addCriterion("OWNER_NAME not like", value, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameIn(List<String> values) {
            addCriterion("OWNER_NAME in", values, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotIn(List<String> values) {
            addCriterion("OWNER_NAME not in", values, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameBetween(String value1, String value2) {
            addCriterion("OWNER_NAME between", value1, value2, "ownerName");
            return (Criteria) this;
        }

        public Criteria andOwnerNameNotBetween(String value1, String value2) {
            addCriterion("OWNER_NAME not between", value1, value2, "ownerName");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneIsNull() {
            addCriterion("LINK_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneIsNotNull() {
            addCriterion("LINK_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneEqualTo(String value) {
            addCriterion("LINK_PHONE =", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotEqualTo(String value) {
            addCriterion("LINK_PHONE <>", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneGreaterThan(String value) {
            addCriterion("LINK_PHONE >", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("LINK_PHONE >=", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneLessThan(String value) {
            addCriterion("LINK_PHONE <", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneLessThanOrEqualTo(String value) {
            addCriterion("LINK_PHONE <=", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneLike(String value) {
            addCriterion("LINK_PHONE like", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotLike(String value) {
            addCriterion("LINK_PHONE not like", value, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneIn(List<String> values) {
            addCriterion("LINK_PHONE in", values, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotIn(List<String> values) {
            addCriterion("LINK_PHONE not in", values, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneBetween(String value1, String value2) {
            addCriterion("LINK_PHONE between", value1, value2, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andLinkPhoneNotBetween(String value1, String value2) {
            addCriterion("LINK_PHONE not between", value1, value2, "linkPhone");
            return (Criteria) this;
        }

        public Criteria andCertCodeIsNull() {
            addCriterion("CERT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCertCodeIsNotNull() {
            addCriterion("CERT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCertCodeEqualTo(String value) {
            addCriterion("CERT_CODE =", value, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeNotEqualTo(String value) {
            addCriterion("CERT_CODE <>", value, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeGreaterThan(String value) {
            addCriterion("CERT_CODE >", value, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CERT_CODE >=", value, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeLessThan(String value) {
            addCriterion("CERT_CODE <", value, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeLessThanOrEqualTo(String value) {
            addCriterion("CERT_CODE <=", value, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeLike(String value) {
            addCriterion("CERT_CODE like", value, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeNotLike(String value) {
            addCriterion("CERT_CODE not like", value, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeIn(List<String> values) {
            addCriterion("CERT_CODE in", values, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeNotIn(List<String> values) {
            addCriterion("CERT_CODE not in", values, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeBetween(String value1, String value2) {
            addCriterion("CERT_CODE between", value1, value2, "certCode");
            return (Criteria) this;
        }

        public Criteria andCertCodeNotBetween(String value1, String value2) {
            addCriterion("CERT_CODE not between", value1, value2, "certCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeIsNull() {
            addCriterion("PROP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPropCodeIsNotNull() {
            addCriterion("PROP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPropCodeEqualTo(String value) {
            addCriterion("PROP_CODE =", value, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeNotEqualTo(String value) {
            addCriterion("PROP_CODE <>", value, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeGreaterThan(String value) {
            addCriterion("PROP_CODE >", value, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PROP_CODE >=", value, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeLessThan(String value) {
            addCriterion("PROP_CODE <", value, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeLessThanOrEqualTo(String value) {
            addCriterion("PROP_CODE <=", value, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeLike(String value) {
            addCriterion("PROP_CODE like", value, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeNotLike(String value) {
            addCriterion("PROP_CODE not like", value, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeIn(List<String> values) {
            addCriterion("PROP_CODE in", values, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeNotIn(List<String> values) {
            addCriterion("PROP_CODE not in", values, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeBetween(String value1, String value2) {
            addCriterion("PROP_CODE between", value1, value2, "propCode");
            return (Criteria) this;
        }

        public Criteria andPropCodeNotBetween(String value1, String value2) {
            addCriterion("PROP_CODE not between", value1, value2, "propCode");
            return (Criteria) this;
        }

        public Criteria andDistNameIsNull() {
            addCriterion("DIST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDistNameIsNotNull() {
            addCriterion("DIST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDistNameEqualTo(String value) {
            addCriterion("DIST_NAME =", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameNotEqualTo(String value) {
            addCriterion("DIST_NAME <>", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameGreaterThan(String value) {
            addCriterion("DIST_NAME >", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameGreaterThanOrEqualTo(String value) {
            addCriterion("DIST_NAME >=", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameLessThan(String value) {
            addCriterion("DIST_NAME <", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameLessThanOrEqualTo(String value) {
            addCriterion("DIST_NAME <=", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameLike(String value) {
            addCriterion("DIST_NAME like", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameNotLike(String value) {
            addCriterion("DIST_NAME not like", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameIn(List<String> values) {
            addCriterion("DIST_NAME in", values, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameNotIn(List<String> values) {
            addCriterion("DIST_NAME not in", values, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameBetween(String value1, String value2) {
            addCriterion("DIST_NAME between", value1, value2, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameNotBetween(String value1, String value2) {
            addCriterion("DIST_NAME not between", value1, value2, "distName");
            return (Criteria) this;
        }

        public Criteria andSectIdIsNull() {
            addCriterion("SECT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSectIdIsNotNull() {
            addCriterion("SECT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSectIdEqualTo(BigDecimal value) {
            addCriterion("SECT_ID =", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdNotEqualTo(BigDecimal value) {
            addCriterion("SECT_ID <>", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdGreaterThan(BigDecimal value) {
            addCriterion("SECT_ID >", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SECT_ID >=", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdLessThan(BigDecimal value) {
            addCriterion("SECT_ID <", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SECT_ID <=", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdIn(List<BigDecimal> values) {
            addCriterion("SECT_ID in", values, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdNotIn(List<BigDecimal> values) {
            addCriterion("SECT_ID not in", values, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SECT_ID between", value1, value2, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SECT_ID not between", value1, value2, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectNameIsNull() {
            addCriterion("SECT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSectNameIsNotNull() {
            addCriterion("SECT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSectNameEqualTo(String value) {
            addCriterion("SECT_NAME =", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameNotEqualTo(String value) {
            addCriterion("SECT_NAME <>", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameGreaterThan(String value) {
            addCriterion("SECT_NAME >", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameGreaterThanOrEqualTo(String value) {
            addCriterion("SECT_NAME >=", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameLessThan(String value) {
            addCriterion("SECT_NAME <", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameLessThanOrEqualTo(String value) {
            addCriterion("SECT_NAME <=", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameLike(String value) {
            addCriterion("SECT_NAME like", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameNotLike(String value) {
            addCriterion("SECT_NAME not like", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameIn(List<String> values) {
            addCriterion("SECT_NAME in", values, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameNotIn(List<String> values) {
            addCriterion("SECT_NAME not in", values, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameBetween(String value1, String value2) {
            addCriterion("SECT_NAME between", value1, value2, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameNotBetween(String value1, String value2) {
            addCriterion("SECT_NAME not between", value1, value2, "sectName");
            return (Criteria) this;
        }

        public Criteria andBuildCodeIsNull() {
            addCriterion("BUILD_CODE is null");
            return (Criteria) this;
        }

        public Criteria andBuildCodeIsNotNull() {
            addCriterion("BUILD_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andBuildCodeEqualTo(String value) {
            addCriterion("BUILD_CODE =", value, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeNotEqualTo(String value) {
            addCriterion("BUILD_CODE <>", value, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeGreaterThan(String value) {
            addCriterion("BUILD_CODE >", value, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeGreaterThanOrEqualTo(String value) {
            addCriterion("BUILD_CODE >=", value, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeLessThan(String value) {
            addCriterion("BUILD_CODE <", value, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeLessThanOrEqualTo(String value) {
            addCriterion("BUILD_CODE <=", value, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeLike(String value) {
            addCriterion("BUILD_CODE like", value, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeNotLike(String value) {
            addCriterion("BUILD_CODE not like", value, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeIn(List<String> values) {
            addCriterion("BUILD_CODE in", values, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeNotIn(List<String> values) {
            addCriterion("BUILD_CODE not in", values, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeBetween(String value1, String value2) {
            addCriterion("BUILD_CODE between", value1, value2, "buildCode");
            return (Criteria) this;
        }

        public Criteria andBuildCodeNotBetween(String value1, String value2) {
            addCriterion("BUILD_CODE not between", value1, value2, "buildCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeIsNull() {
            addCriterion("UNIT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andUnitCodeIsNotNull() {
            addCriterion("UNIT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andUnitCodeEqualTo(String value) {
            addCriterion("UNIT_CODE =", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotEqualTo(String value) {
            addCriterion("UNIT_CODE <>", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeGreaterThan(String value) {
            addCriterion("UNIT_CODE >", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT_CODE >=", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeLessThan(String value) {
            addCriterion("UNIT_CODE <", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeLessThanOrEqualTo(String value) {
            addCriterion("UNIT_CODE <=", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeLike(String value) {
            addCriterion("UNIT_CODE like", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotLike(String value) {
            addCriterion("UNIT_CODE not like", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeIn(List<String> values) {
            addCriterion("UNIT_CODE in", values, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotIn(List<String> values) {
            addCriterion("UNIT_CODE not in", values, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeBetween(String value1, String value2) {
            addCriterion("UNIT_CODE between", value1, value2, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotBetween(String value1, String value2) {
            addCriterion("UNIT_CODE not between", value1, value2, "unitCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeIsNull() {
            addCriterion("FLOOR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andFloorCodeIsNotNull() {
            addCriterion("FLOOR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andFloorCodeEqualTo(String value) {
            addCriterion("FLOOR_CODE =", value, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeNotEqualTo(String value) {
            addCriterion("FLOOR_CODE <>", value, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeGreaterThan(String value) {
            addCriterion("FLOOR_CODE >", value, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FLOOR_CODE >=", value, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeLessThan(String value) {
            addCriterion("FLOOR_CODE <", value, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeLessThanOrEqualTo(String value) {
            addCriterion("FLOOR_CODE <=", value, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeLike(String value) {
            addCriterion("FLOOR_CODE like", value, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeNotLike(String value) {
            addCriterion("FLOOR_CODE not like", value, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeIn(List<String> values) {
            addCriterion("FLOOR_CODE in", values, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeNotIn(List<String> values) {
            addCriterion("FLOOR_CODE not in", values, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeBetween(String value1, String value2) {
            addCriterion("FLOOR_CODE between", value1, value2, "floorCode");
            return (Criteria) this;
        }

        public Criteria andFloorCodeNotBetween(String value1, String value2) {
            addCriterion("FLOOR_CODE not between", value1, value2, "floorCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeIsNull() {
            addCriterion("ROOM_CODE is null");
            return (Criteria) this;
        }

        public Criteria andRoomCodeIsNotNull() {
            addCriterion("ROOM_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomCodeEqualTo(String value) {
            addCriterion("ROOM_CODE =", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeNotEqualTo(String value) {
            addCriterion("ROOM_CODE <>", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeGreaterThan(String value) {
            addCriterion("ROOM_CODE >", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_CODE >=", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeLessThan(String value) {
            addCriterion("ROOM_CODE <", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeLessThanOrEqualTo(String value) {
            addCriterion("ROOM_CODE <=", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeLike(String value) {
            addCriterion("ROOM_CODE like", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeNotLike(String value) {
            addCriterion("ROOM_CODE not like", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeIn(List<String> values) {
            addCriterion("ROOM_CODE in", values, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeNotIn(List<String> values) {
            addCriterion("ROOM_CODE not in", values, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeBetween(String value1, String value2) {
            addCriterion("ROOM_CODE between", value1, value2, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeNotBetween(String value1, String value2) {
            addCriterion("ROOM_CODE not between", value1, value2, "roomCode");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNull() {
            addCriterion("HOUSE_ID is null");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNotNull() {
            addCriterion("HOUSE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHouseIdEqualTo(String value) {
            addCriterion("HOUSE_ID =", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotEqualTo(String value) {
            addCriterion("HOUSE_ID <>", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThan(String value) {
            addCriterion("HOUSE_ID >", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_ID >=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThan(String value) {
            addCriterion("HOUSE_ID <", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_ID <=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLike(String value) {
            addCriterion("HOUSE_ID like", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotLike(String value) {
            addCriterion("HOUSE_ID not like", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdIn(List<String> values) {
            addCriterion("HOUSE_ID in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotIn(List<String> values) {
            addCriterion("HOUSE_ID not in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdBetween(String value1, String value2) {
            addCriterion("HOUSE_ID between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotBetween(String value1, String value2) {
            addCriterion("HOUSE_ID not between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateWaysIsNull() {
            addCriterion("CREATE_WAYS is null");
            return (Criteria) this;
        }

        public Criteria andCreateWaysIsNotNull() {
            addCriterion("CREATE_WAYS is not null");
            return (Criteria) this;
        }

        public Criteria andCreateWaysEqualTo(String value) {
            addCriterion("CREATE_WAYS =", value, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysNotEqualTo(String value) {
            addCriterion("CREATE_WAYS <>", value, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysGreaterThan(String value) {
            addCriterion("CREATE_WAYS >", value, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_WAYS >=", value, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysLessThan(String value) {
            addCriterion("CREATE_WAYS <", value, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysLessThanOrEqualTo(String value) {
            addCriterion("CREATE_WAYS <=", value, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysLike(String value) {
            addCriterion("CREATE_WAYS like", value, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysNotLike(String value) {
            addCriterion("CREATE_WAYS not like", value, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysIn(List<String> values) {
            addCriterion("CREATE_WAYS in", values, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysNotIn(List<String> values) {
            addCriterion("CREATE_WAYS not in", values, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysBetween(String value1, String value2) {
            addCriterion("CREATE_WAYS between", value1, value2, "createWays");
            return (Criteria) this;
        }

        public Criteria andCreateWaysNotBetween(String value1, String value2) {
            addCriterion("CREATE_WAYS not between", value1, value2, "createWays");
            return (Criteria) this;
        }

        public Criteria andInfoStatusIsNull() {
            addCriterion("INFO_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andInfoStatusIsNotNull() {
            addCriterion("INFO_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andInfoStatusEqualTo(String value) {
            addCriterion("INFO_STATUS =", value, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusNotEqualTo(String value) {
            addCriterion("INFO_STATUS <>", value, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusGreaterThan(String value) {
            addCriterion("INFO_STATUS >", value, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_STATUS >=", value, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusLessThan(String value) {
            addCriterion("INFO_STATUS <", value, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusLessThanOrEqualTo(String value) {
            addCriterion("INFO_STATUS <=", value, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusLike(String value) {
            addCriterion("INFO_STATUS like", value, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusNotLike(String value) {
            addCriterion("INFO_STATUS not like", value, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusIn(List<String> values) {
            addCriterion("INFO_STATUS in", values, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusNotIn(List<String> values) {
            addCriterion("INFO_STATUS not in", values, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusBetween(String value1, String value2) {
            addCriterion("INFO_STATUS between", value1, value2, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoStatusNotBetween(String value1, String value2) {
            addCriterion("INFO_STATUS not between", value1, value2, "infoStatus");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkIsNull() {
            addCriterion("INFO_REMARK is null");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkIsNotNull() {
            addCriterion("INFO_REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkEqualTo(String value) {
            addCriterion("INFO_REMARK =", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkNotEqualTo(String value) {
            addCriterion("INFO_REMARK <>", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkGreaterThan(String value) {
            addCriterion("INFO_REMARK >", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_REMARK >=", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkLessThan(String value) {
            addCriterion("INFO_REMARK <", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkLessThanOrEqualTo(String value) {
            addCriterion("INFO_REMARK <=", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkLike(String value) {
            addCriterion("INFO_REMARK like", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkNotLike(String value) {
            addCriterion("INFO_REMARK not like", value, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkIn(List<String> values) {
            addCriterion("INFO_REMARK in", values, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkNotIn(List<String> values) {
            addCriterion("INFO_REMARK not in", values, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkBetween(String value1, String value2) {
            addCriterion("INFO_REMARK between", value1, value2, "infoRemark");
            return (Criteria) this;
        }

        public Criteria andInfoRemarkNotBetween(String value1, String value2) {
            addCriterion("INFO_REMARK not between", value1, value2, "infoRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 12 18:41:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_HOUSE_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}