package com.indihx.elecvote.entity;

import java.math.BigDecimal;

public class VoteResultInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.RESULT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal resultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.VOTE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String voteDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.VOTE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String voteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.VOTE_WAYS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String voteWays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.VOTE_RESULT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String voteResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.USER_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.USER_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.RESULT_ID
     *
     * @return the value of VOTE_RESULT_INFO.RESULT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.RESULT_ID
     *
     * @param resultId the value for VOTE_RESULT_INFO.RESULT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setResultId(BigDecimal resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.TOPIC_ID
     *
     * @return the value of VOTE_RESULT_INFO.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.TOPIC_ID
     *
     * @param topicId the value for VOTE_RESULT_INFO.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setTopicId(BigDecimal topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.INFO_ID
     *
     * @return the value of VOTE_RESULT_INFO.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.INFO_ID
     *
     * @param infoId the value for VOTE_RESULT_INFO.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setInfoId(BigDecimal infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.VOTE_DATE
     *
     * @return the value of VOTE_RESULT_INFO.VOTE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getVoteDate() {
        return voteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.VOTE_DATE
     *
     * @param voteDate the value for VOTE_RESULT_INFO.VOTE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setVoteDate(String voteDate) {
        this.voteDate = voteDate == null ? null : voteDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.VOTE_TIME
     *
     * @return the value of VOTE_RESULT_INFO.VOTE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getVoteTime() {
        return voteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.VOTE_TIME
     *
     * @param voteTime the value for VOTE_RESULT_INFO.VOTE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setVoteTime(String voteTime) {
        this.voteTime = voteTime == null ? null : voteTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.VOTE_WAYS
     *
     * @return the value of VOTE_RESULT_INFO.VOTE_WAYS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getVoteWays() {
        return voteWays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.VOTE_WAYS
     *
     * @param voteWays the value for VOTE_RESULT_INFO.VOTE_WAYS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setVoteWays(String voteWays) {
        this.voteWays = voteWays == null ? null : voteWays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.VOTE_RESULT
     *
     * @return the value of VOTE_RESULT_INFO.VOTE_RESULT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getVoteResult() {
        return voteResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.VOTE_RESULT
     *
     * @param voteResult the value for VOTE_RESULT_INFO.VOTE_RESULT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setVoteResult(String voteResult) {
        this.voteResult = voteResult == null ? null : voteResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.USER_ID
     *
     * @return the value of VOTE_RESULT_INFO.USER_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.USER_ID
     *
     * @param userId the value for VOTE_RESULT_INFO.USER_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.USER_NAME
     *
     * @return the value of VOTE_RESULT_INFO.USER_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.USER_NAME
     *
     * @param userName the value for VOTE_RESULT_INFO.USER_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.CREATE_DATE
     *
     * @return the value of VOTE_RESULT_INFO.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.CREATE_DATE
     *
     * @param createDate the value for VOTE_RESULT_INFO.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_INFO.CREATE_TIME
     *
     * @return the value of VOTE_RESULT_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_INFO.CREATE_TIME
     *
     * @param createTime the value for VOTE_RESULT_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}