package com.indihx.elecvote.entity;

import java.math.BigDecimal;

public class VoteOwnerHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_OWNER_HISTORY.RECORD_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_OWNER_HISTORY.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_OWNER_HISTORY.INFO_ADDR
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String infoAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_OWNER_HISTORY.OWNER_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String ownerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_OWNER_HISTORY.LINK_PHONE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String linkPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_OWNER_HISTORY.CERT_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String certCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_OWNER_HISTORY.PORP_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String porpCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_OWNER_HISTORY.RECORD_ID
     *
     * @return the value of VOTE_OWNER_HISTORY.RECORD_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_OWNER_HISTORY.RECORD_ID
     *
     * @param recordId the value for VOTE_OWNER_HISTORY.RECORD_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_OWNER_HISTORY.INFO_ID
     *
     * @return the value of VOTE_OWNER_HISTORY.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_OWNER_HISTORY.INFO_ID
     *
     * @param infoId the value for VOTE_OWNER_HISTORY.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setInfoId(BigDecimal infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_OWNER_HISTORY.INFO_ADDR
     *
     * @return the value of VOTE_OWNER_HISTORY.INFO_ADDR
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getInfoAddr() {
        return infoAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_OWNER_HISTORY.INFO_ADDR
     *
     * @param infoAddr the value for VOTE_OWNER_HISTORY.INFO_ADDR
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setInfoAddr(String infoAddr) {
        this.infoAddr = infoAddr == null ? null : infoAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_OWNER_HISTORY.OWNER_NAME
     *
     * @return the value of VOTE_OWNER_HISTORY.OWNER_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_OWNER_HISTORY.OWNER_NAME
     *
     * @param ownerName the value for VOTE_OWNER_HISTORY.OWNER_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_OWNER_HISTORY.LINK_PHONE
     *
     * @return the value of VOTE_OWNER_HISTORY.LINK_PHONE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_OWNER_HISTORY.LINK_PHONE
     *
     * @param linkPhone the value for VOTE_OWNER_HISTORY.LINK_PHONE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone == null ? null : linkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_OWNER_HISTORY.CERT_CODE
     *
     * @return the value of VOTE_OWNER_HISTORY.CERT_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getCertCode() {
        return certCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_OWNER_HISTORY.CERT_CODE
     *
     * @param certCode the value for VOTE_OWNER_HISTORY.CERT_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setCertCode(String certCode) {
        this.certCode = certCode == null ? null : certCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_OWNER_HISTORY.PORP_CODE
     *
     * @return the value of VOTE_OWNER_HISTORY.PORP_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getPorpCode() {
        return porpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_OWNER_HISTORY.PORP_CODE
     *
     * @param porpCode the value for VOTE_OWNER_HISTORY.PORP_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setPorpCode(String porpCode) {
        this.porpCode = porpCode == null ? null : porpCode.trim();
    }
}