package com.indihx.elecvote.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class VoteSectInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public VoteSectInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSectIdIsNull() {
            addCriterion("SECT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSectIdIsNotNull() {
            addCriterion("SECT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSectIdEqualTo(BigDecimal value) {
            addCriterion("SECT_ID =", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdNotEqualTo(BigDecimal value) {
            addCriterion("SECT_ID <>", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdGreaterThan(BigDecimal value) {
            addCriterion("SECT_ID >", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SECT_ID >=", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdLessThan(BigDecimal value) {
            addCriterion("SECT_ID <", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SECT_ID <=", value, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdIn(List<BigDecimal> values) {
            addCriterion("SECT_ID in", values, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdNotIn(List<BigDecimal> values) {
            addCriterion("SECT_ID not in", values, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SECT_ID between", value1, value2, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SECT_ID not between", value1, value2, "sectId");
            return (Criteria) this;
        }

        public Criteria andSectNameIsNull() {
            addCriterion("SECT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSectNameIsNotNull() {
            addCriterion("SECT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSectNameEqualTo(String value) {
            addCriterion("SECT_NAME =", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameNotEqualTo(String value) {
            addCriterion("SECT_NAME <>", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameGreaterThan(String value) {
            addCriterion("SECT_NAME >", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameGreaterThanOrEqualTo(String value) {
            addCriterion("SECT_NAME >=", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameLessThan(String value) {
            addCriterion("SECT_NAME <", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameLessThanOrEqualTo(String value) {
            addCriterion("SECT_NAME <=", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameLike(String value) {
            addCriterion("SECT_NAME like", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameNotLike(String value) {
            addCriterion("SECT_NAME not like", value, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameIn(List<String> values) {
            addCriterion("SECT_NAME in", values, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameNotIn(List<String> values) {
            addCriterion("SECT_NAME not in", values, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameBetween(String value1, String value2) {
            addCriterion("SECT_NAME between", value1, value2, "sectName");
            return (Criteria) this;
        }

        public Criteria andSectNameNotBetween(String value1, String value2) {
            addCriterion("SECT_NAME not between", value1, value2, "sectName");
            return (Criteria) this;
        }

        public Criteria andDistNameIsNull() {
            addCriterion("DIST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDistNameIsNotNull() {
            addCriterion("DIST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDistNameEqualTo(String value) {
            addCriterion("DIST_NAME =", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameNotEqualTo(String value) {
            addCriterion("DIST_NAME <>", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameGreaterThan(String value) {
            addCriterion("DIST_NAME >", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameGreaterThanOrEqualTo(String value) {
            addCriterion("DIST_NAME >=", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameLessThan(String value) {
            addCriterion("DIST_NAME <", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameLessThanOrEqualTo(String value) {
            addCriterion("DIST_NAME <=", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameLike(String value) {
            addCriterion("DIST_NAME like", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameNotLike(String value) {
            addCriterion("DIST_NAME not like", value, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameIn(List<String> values) {
            addCriterion("DIST_NAME in", values, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameNotIn(List<String> values) {
            addCriterion("DIST_NAME not in", values, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameBetween(String value1, String value2) {
            addCriterion("DIST_NAME between", value1, value2, "distName");
            return (Criteria) this;
        }

        public Criteria andDistNameNotBetween(String value1, String value2) {
            addCriterion("DIST_NAME not between", value1, value2, "distName");
            return (Criteria) this;
        }

        public Criteria andSectAddrIsNull() {
            addCriterion("SECT_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andSectAddrIsNotNull() {
            addCriterion("SECT_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andSectAddrEqualTo(String value) {
            addCriterion("SECT_ADDR =", value, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrNotEqualTo(String value) {
            addCriterion("SECT_ADDR <>", value, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrGreaterThan(String value) {
            addCriterion("SECT_ADDR >", value, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrGreaterThanOrEqualTo(String value) {
            addCriterion("SECT_ADDR >=", value, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrLessThan(String value) {
            addCriterion("SECT_ADDR <", value, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrLessThanOrEqualTo(String value) {
            addCriterion("SECT_ADDR <=", value, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrLike(String value) {
            addCriterion("SECT_ADDR like", value, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrNotLike(String value) {
            addCriterion("SECT_ADDR not like", value, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrIn(List<String> values) {
            addCriterion("SECT_ADDR in", values, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrNotIn(List<String> values) {
            addCriterion("SECT_ADDR not in", values, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrBetween(String value1, String value2) {
            addCriterion("SECT_ADDR between", value1, value2, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andSectAddrNotBetween(String value1, String value2) {
            addCriterion("SECT_ADDR not between", value1, value2, "sectAddr");
            return (Criteria) this;
        }

        public Criteria andHouCountIsNull() {
            addCriterion("HOU_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andHouCountIsNotNull() {
            addCriterion("HOU_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andHouCountEqualTo(Long value) {
            addCriterion("HOU_COUNT =", value, "houCount");
            return (Criteria) this;
        }

        public Criteria andHouCountNotEqualTo(Long value) {
            addCriterion("HOU_COUNT <>", value, "houCount");
            return (Criteria) this;
        }

        public Criteria andHouCountGreaterThan(Long value) {
            addCriterion("HOU_COUNT >", value, "houCount");
            return (Criteria) this;
        }

        public Criteria andHouCountGreaterThanOrEqualTo(Long value) {
            addCriterion("HOU_COUNT >=", value, "houCount");
            return (Criteria) this;
        }

        public Criteria andHouCountLessThan(Long value) {
            addCriterion("HOU_COUNT <", value, "houCount");
            return (Criteria) this;
        }

        public Criteria andHouCountLessThanOrEqualTo(Long value) {
            addCriterion("HOU_COUNT <=", value, "houCount");
            return (Criteria) this;
        }

        public Criteria andHouCountIn(List<Long> values) {
            addCriterion("HOU_COUNT in", values, "houCount");
            return (Criteria) this;
        }

        public Criteria andHouCountNotIn(List<Long> values) {
            addCriterion("HOU_COUNT not in", values, "houCount");
            return (Criteria) this;
        }

        public Criteria andHouCountBetween(Long value1, Long value2) {
            addCriterion("HOU_COUNT between", value1, value2, "houCount");
            return (Criteria) this;
        }

        public Criteria andHouCountNotBetween(Long value1, Long value2) {
            addCriterion("HOU_COUNT not between", value1, value2, "houCount");
            return (Criteria) this;
        }

        public Criteria andBuildCountIsNull() {
            addCriterion("BUILD_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andBuildCountIsNotNull() {
            addCriterion("BUILD_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andBuildCountEqualTo(Long value) {
            addCriterion("BUILD_COUNT =", value, "buildCount");
            return (Criteria) this;
        }

        public Criteria andBuildCountNotEqualTo(Long value) {
            addCriterion("BUILD_COUNT <>", value, "buildCount");
            return (Criteria) this;
        }

        public Criteria andBuildCountGreaterThan(Long value) {
            addCriterion("BUILD_COUNT >", value, "buildCount");
            return (Criteria) this;
        }

        public Criteria andBuildCountGreaterThanOrEqualTo(Long value) {
            addCriterion("BUILD_COUNT >=", value, "buildCount");
            return (Criteria) this;
        }

        public Criteria andBuildCountLessThan(Long value) {
            addCriterion("BUILD_COUNT <", value, "buildCount");
            return (Criteria) this;
        }

        public Criteria andBuildCountLessThanOrEqualTo(Long value) {
            addCriterion("BUILD_COUNT <=", value, "buildCount");
            return (Criteria) this;
        }

        public Criteria andBuildCountIn(List<Long> values) {
            addCriterion("BUILD_COUNT in", values, "buildCount");
            return (Criteria) this;
        }

        public Criteria andBuildCountNotIn(List<Long> values) {
            addCriterion("BUILD_COUNT not in", values, "buildCount");
            return (Criteria) this;
        }

        public Criteria andBuildCountBetween(Long value1, Long value2) {
            addCriterion("BUILD_COUNT between", value1, value2, "buildCount");
            return (Criteria) this;
        }

        public Criteria andBuildCountNotBetween(Long value1, Long value2) {
            addCriterion("BUILD_COUNT not between", value1, value2, "buildCount");
            return (Criteria) this;
        }

        public Criteria andInfoAreaIsNull() {
            addCriterion("INFO_AREA is null");
            return (Criteria) this;
        }

        public Criteria andInfoAreaIsNotNull() {
            addCriterion("INFO_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andInfoAreaEqualTo(BigDecimal value) {
            addCriterion("INFO_AREA =", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaNotEqualTo(BigDecimal value) {
            addCriterion("INFO_AREA <>", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaGreaterThan(BigDecimal value) {
            addCriterion("INFO_AREA >", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INFO_AREA >=", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaLessThan(BigDecimal value) {
            addCriterion("INFO_AREA <", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INFO_AREA <=", value, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaIn(List<BigDecimal> values) {
            addCriterion("INFO_AREA in", values, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaNotIn(List<BigDecimal> values) {
            addCriterion("INFO_AREA not in", values, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INFO_AREA between", value1, value2, "infoArea");
            return (Criteria) this;
        }

        public Criteria andInfoAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INFO_AREA not between", value1, value2, "infoArea");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 12 18:41:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_SECT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}