package com.indihx.elecvote.entity;

import java.math.BigDecimal;

public class VoteSectInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SECT_INFO.SECT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal sectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SECT_INFO.SECT_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String sectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SECT_INFO.DIST_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String distName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SECT_INFO.SECT_ADDR
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String sectAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SECT_INFO.HOU_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private Long houCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SECT_INFO.BUILD_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private Long buildCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SECT_INFO.INFO_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal infoArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SECT_INFO.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SECT_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SECT_INFO.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SECT_INFO.SECT_ID
     *
     * @return the value of VOTE_SECT_INFO.SECT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getSectId() {
        return sectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SECT_INFO.SECT_ID
     *
     * @param sectId the value for VOTE_SECT_INFO.SECT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setSectId(BigDecimal sectId) {
        this.sectId = sectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SECT_INFO.SECT_NAME
     *
     * @return the value of VOTE_SECT_INFO.SECT_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getSectName() {
        return sectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SECT_INFO.SECT_NAME
     *
     * @param sectName the value for VOTE_SECT_INFO.SECT_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setSectName(String sectName) {
        this.sectName = sectName == null ? null : sectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SECT_INFO.DIST_NAME
     *
     * @return the value of VOTE_SECT_INFO.DIST_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getDistName() {
        return distName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SECT_INFO.DIST_NAME
     *
     * @param distName the value for VOTE_SECT_INFO.DIST_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setDistName(String distName) {
        this.distName = distName == null ? null : distName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SECT_INFO.SECT_ADDR
     *
     * @return the value of VOTE_SECT_INFO.SECT_ADDR
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getSectAddr() {
        return sectAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SECT_INFO.SECT_ADDR
     *
     * @param sectAddr the value for VOTE_SECT_INFO.SECT_ADDR
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setSectAddr(String sectAddr) {
        this.sectAddr = sectAddr == null ? null : sectAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SECT_INFO.HOU_COUNT
     *
     * @return the value of VOTE_SECT_INFO.HOU_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Long getHouCount() {
        return houCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SECT_INFO.HOU_COUNT
     *
     * @param houCount the value for VOTE_SECT_INFO.HOU_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setHouCount(Long houCount) {
        this.houCount = houCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SECT_INFO.BUILD_COUNT
     *
     * @return the value of VOTE_SECT_INFO.BUILD_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Long getBuildCount() {
        return buildCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SECT_INFO.BUILD_COUNT
     *
     * @param buildCount the value for VOTE_SECT_INFO.BUILD_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setBuildCount(Long buildCount) {
        this.buildCount = buildCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SECT_INFO.INFO_AREA
     *
     * @return the value of VOTE_SECT_INFO.INFO_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getInfoArea() {
        return infoArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SECT_INFO.INFO_AREA
     *
     * @param infoArea the value for VOTE_SECT_INFO.INFO_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setInfoArea(BigDecimal infoArea) {
        this.infoArea = infoArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SECT_INFO.CREATE_DATE
     *
     * @return the value of VOTE_SECT_INFO.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SECT_INFO.CREATE_DATE
     *
     * @param createDate the value for VOTE_SECT_INFO.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SECT_INFO.CREATE_TIME
     *
     * @return the value of VOTE_SECT_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SECT_INFO.CREATE_TIME
     *
     * @param createTime the value for VOTE_SECT_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SECT_INFO.REMARK
     *
     * @return the value of VOTE_SECT_INFO.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SECT_INFO.REMARK
     *
     * @param remark the value for VOTE_SECT_INFO.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}