package com.indihx.elecvote.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class VoteResultInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public VoteResultInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andResultIdIsNull() {
            addCriterion("RESULT_ID is null");
            return (Criteria) this;
        }

        public Criteria andResultIdIsNotNull() {
            addCriterion("RESULT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andResultIdEqualTo(BigDecimal value) {
            addCriterion("RESULT_ID =", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdNotEqualTo(BigDecimal value) {
            addCriterion("RESULT_ID <>", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdGreaterThan(BigDecimal value) {
            addCriterion("RESULT_ID >", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RESULT_ID >=", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdLessThan(BigDecimal value) {
            addCriterion("RESULT_ID <", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RESULT_ID <=", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdIn(List<BigDecimal> values) {
            addCriterion("RESULT_ID in", values, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdNotIn(List<BigDecimal> values) {
            addCriterion("RESULT_ID not in", values, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RESULT_ID between", value1, value2, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RESULT_ID not between", value1, value2, "resultId");
            return (Criteria) this;
        }

        public Criteria andTopicIdIsNull() {
            addCriterion("TOPIC_ID is null");
            return (Criteria) this;
        }

        public Criteria andTopicIdIsNotNull() {
            addCriterion("TOPIC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTopicIdEqualTo(BigDecimal value) {
            addCriterion("TOPIC_ID =", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotEqualTo(BigDecimal value) {
            addCriterion("TOPIC_ID <>", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdGreaterThan(BigDecimal value) {
            addCriterion("TOPIC_ID >", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOPIC_ID >=", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdLessThan(BigDecimal value) {
            addCriterion("TOPIC_ID <", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOPIC_ID <=", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdIn(List<BigDecimal> values) {
            addCriterion("TOPIC_ID in", values, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotIn(List<BigDecimal> values) {
            addCriterion("TOPIC_ID not in", values, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOPIC_ID between", value1, value2, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOPIC_ID not between", value1, value2, "topicId");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNull() {
            addCriterion("INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNotNull() {
            addCriterion("INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIdEqualTo(BigDecimal value) {
            addCriterion("INFO_ID =", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotEqualTo(BigDecimal value) {
            addCriterion("INFO_ID <>", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThan(BigDecimal value) {
            addCriterion("INFO_ID >", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INFO_ID >=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThan(BigDecimal value) {
            addCriterion("INFO_ID <", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INFO_ID <=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdIn(List<BigDecimal> values) {
            addCriterion("INFO_ID in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotIn(List<BigDecimal> values) {
            addCriterion("INFO_ID not in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INFO_ID between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INFO_ID not between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andVoteDateIsNull() {
            addCriterion("VOTE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andVoteDateIsNotNull() {
            addCriterion("VOTE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andVoteDateEqualTo(String value) {
            addCriterion("VOTE_DATE =", value, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateNotEqualTo(String value) {
            addCriterion("VOTE_DATE <>", value, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateGreaterThan(String value) {
            addCriterion("VOTE_DATE >", value, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateGreaterThanOrEqualTo(String value) {
            addCriterion("VOTE_DATE >=", value, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateLessThan(String value) {
            addCriterion("VOTE_DATE <", value, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateLessThanOrEqualTo(String value) {
            addCriterion("VOTE_DATE <=", value, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateLike(String value) {
            addCriterion("VOTE_DATE like", value, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateNotLike(String value) {
            addCriterion("VOTE_DATE not like", value, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateIn(List<String> values) {
            addCriterion("VOTE_DATE in", values, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateNotIn(List<String> values) {
            addCriterion("VOTE_DATE not in", values, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateBetween(String value1, String value2) {
            addCriterion("VOTE_DATE between", value1, value2, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteDateNotBetween(String value1, String value2) {
            addCriterion("VOTE_DATE not between", value1, value2, "voteDate");
            return (Criteria) this;
        }

        public Criteria andVoteTimeIsNull() {
            addCriterion("VOTE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andVoteTimeIsNotNull() {
            addCriterion("VOTE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andVoteTimeEqualTo(String value) {
            addCriterion("VOTE_TIME =", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeNotEqualTo(String value) {
            addCriterion("VOTE_TIME <>", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeGreaterThan(String value) {
            addCriterion("VOTE_TIME >", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeGreaterThanOrEqualTo(String value) {
            addCriterion("VOTE_TIME >=", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeLessThan(String value) {
            addCriterion("VOTE_TIME <", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeLessThanOrEqualTo(String value) {
            addCriterion("VOTE_TIME <=", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeLike(String value) {
            addCriterion("VOTE_TIME like", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeNotLike(String value) {
            addCriterion("VOTE_TIME not like", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeIn(List<String> values) {
            addCriterion("VOTE_TIME in", values, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeNotIn(List<String> values) {
            addCriterion("VOTE_TIME not in", values, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeBetween(String value1, String value2) {
            addCriterion("VOTE_TIME between", value1, value2, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeNotBetween(String value1, String value2) {
            addCriterion("VOTE_TIME not between", value1, value2, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteWaysIsNull() {
            addCriterion("VOTE_WAYS is null");
            return (Criteria) this;
        }

        public Criteria andVoteWaysIsNotNull() {
            addCriterion("VOTE_WAYS is not null");
            return (Criteria) this;
        }

        public Criteria andVoteWaysEqualTo(String value) {
            addCriterion("VOTE_WAYS =", value, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysNotEqualTo(String value) {
            addCriterion("VOTE_WAYS <>", value, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysGreaterThan(String value) {
            addCriterion("VOTE_WAYS >", value, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysGreaterThanOrEqualTo(String value) {
            addCriterion("VOTE_WAYS >=", value, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysLessThan(String value) {
            addCriterion("VOTE_WAYS <", value, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysLessThanOrEqualTo(String value) {
            addCriterion("VOTE_WAYS <=", value, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysLike(String value) {
            addCriterion("VOTE_WAYS like", value, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysNotLike(String value) {
            addCriterion("VOTE_WAYS not like", value, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysIn(List<String> values) {
            addCriterion("VOTE_WAYS in", values, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysNotIn(List<String> values) {
            addCriterion("VOTE_WAYS not in", values, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysBetween(String value1, String value2) {
            addCriterion("VOTE_WAYS between", value1, value2, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteWaysNotBetween(String value1, String value2) {
            addCriterion("VOTE_WAYS not between", value1, value2, "voteWays");
            return (Criteria) this;
        }

        public Criteria andVoteResultIsNull() {
            addCriterion("VOTE_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andVoteResultIsNotNull() {
            addCriterion("VOTE_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andVoteResultEqualTo(String value) {
            addCriterion("VOTE_RESULT =", value, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultNotEqualTo(String value) {
            addCriterion("VOTE_RESULT <>", value, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultGreaterThan(String value) {
            addCriterion("VOTE_RESULT >", value, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultGreaterThanOrEqualTo(String value) {
            addCriterion("VOTE_RESULT >=", value, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultLessThan(String value) {
            addCriterion("VOTE_RESULT <", value, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultLessThanOrEqualTo(String value) {
            addCriterion("VOTE_RESULT <=", value, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultLike(String value) {
            addCriterion("VOTE_RESULT like", value, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultNotLike(String value) {
            addCriterion("VOTE_RESULT not like", value, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultIn(List<String> values) {
            addCriterion("VOTE_RESULT in", values, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultNotIn(List<String> values) {
            addCriterion("VOTE_RESULT not in", values, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultBetween(String value1, String value2) {
            addCriterion("VOTE_RESULT between", value1, value2, "voteResult");
            return (Criteria) this;
        }

        public Criteria andVoteResultNotBetween(String value1, String value2) {
            addCriterion("VOTE_RESULT not between", value1, value2, "voteResult");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 12 18:41:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VOTE_RESULT_INFO
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}