package com.indihx.elecvote.entity;

import java.math.BigDecimal;

public class VoteResultSum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.SUM_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private Long sumCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.SUM_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal sumArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.AGREE_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private Long agreeHou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.AGREE_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal agreeHouRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.AGREE_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal agreeArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.AGREE_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal agreeAreaRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.UNAGREE_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private Long unagreeHou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.UNAGREE_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal unagreeHouRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.UNAGREE_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal unagreeArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.UNAGREE_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal unagreeAreaRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.QUIT_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private Long quitHou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.QUIT_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal quitHouRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.QUIT_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal quitArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.QUIT_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal quitAreaRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.NONVOTE_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private Long nonvoteHou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.NONVOTE_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal nonvoteHouRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.NONVOTE_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal nonvoteArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.NONVOTE_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal nonvoteAreaRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_RESULT_SUM.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.TOPIC_ID
     *
     * @return the value of VOTE_RESULT_SUM.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.TOPIC_ID
     *
     * @param topicId the value for VOTE_RESULT_SUM.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setTopicId(BigDecimal topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.SUM_COUNT
     *
     * @return the value of VOTE_RESULT_SUM.SUM_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Long getSumCount() {
        return sumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.SUM_COUNT
     *
     * @param sumCount the value for VOTE_RESULT_SUM.SUM_COUNT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setSumCount(Long sumCount) {
        this.sumCount = sumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.SUM_AREA
     *
     * @return the value of VOTE_RESULT_SUM.SUM_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getSumArea() {
        return sumArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.SUM_AREA
     *
     * @param sumArea the value for VOTE_RESULT_SUM.SUM_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setSumArea(BigDecimal sumArea) {
        this.sumArea = sumArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.AGREE_HOU
     *
     * @return the value of VOTE_RESULT_SUM.AGREE_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Long getAgreeHou() {
        return agreeHou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.AGREE_HOU
     *
     * @param agreeHou the value for VOTE_RESULT_SUM.AGREE_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setAgreeHou(Long agreeHou) {
        this.agreeHou = agreeHou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.AGREE_HOU_RATE
     *
     * @return the value of VOTE_RESULT_SUM.AGREE_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getAgreeHouRate() {
        return agreeHouRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.AGREE_HOU_RATE
     *
     * @param agreeHouRate the value for VOTE_RESULT_SUM.AGREE_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setAgreeHouRate(BigDecimal agreeHouRate) {
        this.agreeHouRate = agreeHouRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.AGREE_AREA
     *
     * @return the value of VOTE_RESULT_SUM.AGREE_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getAgreeArea() {
        return agreeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.AGREE_AREA
     *
     * @param agreeArea the value for VOTE_RESULT_SUM.AGREE_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setAgreeArea(BigDecimal agreeArea) {
        this.agreeArea = agreeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.AGREE_AREA_RATE
     *
     * @return the value of VOTE_RESULT_SUM.AGREE_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getAgreeAreaRate() {
        return agreeAreaRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.AGREE_AREA_RATE
     *
     * @param agreeAreaRate the value for VOTE_RESULT_SUM.AGREE_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setAgreeAreaRate(BigDecimal agreeAreaRate) {
        this.agreeAreaRate = agreeAreaRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.UNAGREE_HOU
     *
     * @return the value of VOTE_RESULT_SUM.UNAGREE_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Long getUnagreeHou() {
        return unagreeHou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.UNAGREE_HOU
     *
     * @param unagreeHou the value for VOTE_RESULT_SUM.UNAGREE_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setUnagreeHou(Long unagreeHou) {
        this.unagreeHou = unagreeHou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.UNAGREE_HOU_RATE
     *
     * @return the value of VOTE_RESULT_SUM.UNAGREE_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getUnagreeHouRate() {
        return unagreeHouRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.UNAGREE_HOU_RATE
     *
     * @param unagreeHouRate the value for VOTE_RESULT_SUM.UNAGREE_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setUnagreeHouRate(BigDecimal unagreeHouRate) {
        this.unagreeHouRate = unagreeHouRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.UNAGREE_AREA
     *
     * @return the value of VOTE_RESULT_SUM.UNAGREE_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getUnagreeArea() {
        return unagreeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.UNAGREE_AREA
     *
     * @param unagreeArea the value for VOTE_RESULT_SUM.UNAGREE_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setUnagreeArea(BigDecimal unagreeArea) {
        this.unagreeArea = unagreeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.UNAGREE_AREA_RATE
     *
     * @return the value of VOTE_RESULT_SUM.UNAGREE_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getUnagreeAreaRate() {
        return unagreeAreaRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.UNAGREE_AREA_RATE
     *
     * @param unagreeAreaRate the value for VOTE_RESULT_SUM.UNAGREE_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setUnagreeAreaRate(BigDecimal unagreeAreaRate) {
        this.unagreeAreaRate = unagreeAreaRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.QUIT_HOU
     *
     * @return the value of VOTE_RESULT_SUM.QUIT_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Long getQuitHou() {
        return quitHou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.QUIT_HOU
     *
     * @param quitHou the value for VOTE_RESULT_SUM.QUIT_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setQuitHou(Long quitHou) {
        this.quitHou = quitHou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.QUIT_HOU_RATE
     *
     * @return the value of VOTE_RESULT_SUM.QUIT_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getQuitHouRate() {
        return quitHouRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.QUIT_HOU_RATE
     *
     * @param quitHouRate the value for VOTE_RESULT_SUM.QUIT_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setQuitHouRate(BigDecimal quitHouRate) {
        this.quitHouRate = quitHouRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.QUIT_AREA
     *
     * @return the value of VOTE_RESULT_SUM.QUIT_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getQuitArea() {
        return quitArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.QUIT_AREA
     *
     * @param quitArea the value for VOTE_RESULT_SUM.QUIT_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setQuitArea(BigDecimal quitArea) {
        this.quitArea = quitArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.QUIT_AREA_RATE
     *
     * @return the value of VOTE_RESULT_SUM.QUIT_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getQuitAreaRate() {
        return quitAreaRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.QUIT_AREA_RATE
     *
     * @param quitAreaRate the value for VOTE_RESULT_SUM.QUIT_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setQuitAreaRate(BigDecimal quitAreaRate) {
        this.quitAreaRate = quitAreaRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.NONVOTE_HOU
     *
     * @return the value of VOTE_RESULT_SUM.NONVOTE_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public Long getNonvoteHou() {
        return nonvoteHou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.NONVOTE_HOU
     *
     * @param nonvoteHou the value for VOTE_RESULT_SUM.NONVOTE_HOU
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setNonvoteHou(Long nonvoteHou) {
        this.nonvoteHou = nonvoteHou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.NONVOTE_HOU_RATE
     *
     * @return the value of VOTE_RESULT_SUM.NONVOTE_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getNonvoteHouRate() {
        return nonvoteHouRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.NONVOTE_HOU_RATE
     *
     * @param nonvoteHouRate the value for VOTE_RESULT_SUM.NONVOTE_HOU_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setNonvoteHouRate(BigDecimal nonvoteHouRate) {
        this.nonvoteHouRate = nonvoteHouRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.NONVOTE_AREA
     *
     * @return the value of VOTE_RESULT_SUM.NONVOTE_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getNonvoteArea() {
        return nonvoteArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.NONVOTE_AREA
     *
     * @param nonvoteArea the value for VOTE_RESULT_SUM.NONVOTE_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setNonvoteArea(BigDecimal nonvoteArea) {
        this.nonvoteArea = nonvoteArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.NONVOTE_AREA_RATE
     *
     * @return the value of VOTE_RESULT_SUM.NONVOTE_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getNonvoteAreaRate() {
        return nonvoteAreaRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.NONVOTE_AREA_RATE
     *
     * @param nonvoteAreaRate the value for VOTE_RESULT_SUM.NONVOTE_AREA_RATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setNonvoteAreaRate(BigDecimal nonvoteAreaRate) {
        this.nonvoteAreaRate = nonvoteAreaRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_RESULT_SUM.REMARK
     *
     * @return the value of VOTE_RESULT_SUM.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_RESULT_SUM.REMARK
     *
     * @param remark the value for VOTE_RESULT_SUM.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}