package com.indihx.elecvote.entity;

import java.math.BigDecimal;

public class VoteScopeInfo extends VoteScopeInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SCOPE_INFO.INFO_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal infoArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_SCOPE_INFO.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SCOPE_INFO.INFO_AREA
     *
     * @return the value of VOTE_SCOPE_INFO.INFO_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getInfoArea() {
        return infoArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SCOPE_INFO.INFO_AREA
     *
     * @param infoArea the value for VOTE_SCOPE_INFO.INFO_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setInfoArea(BigDecimal infoArea) {
        this.infoArea = infoArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_SCOPE_INFO.LAST_MODIFY_TIME
     *
     * @return the value of VOTE_SCOPE_INFO.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_SCOPE_INFO.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for VOTE_SCOPE_INFO.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setLastModifyTime(String lastModifyTime) {
        this.lastModifyTime = lastModifyTime == null ? null : lastModifyTime.trim();
    }
}