package com.indihx.elecvote.entity;

import java.math.BigDecimal;

public class VoteTopicInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.TOPIC_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String topicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.TOPIC_CONTENT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String topicContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.SUM_HS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal sumHs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.SUM_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal sumArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.VOTE_START_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String voteStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.VOTE_END_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String voteEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.VOTE_STATUS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String voteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.APPLY_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String applyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.LINK_PHONE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String linkPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.USER_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.ORG_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.ORG_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.LINK_FLAG
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String linkFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.WS_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal wsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_TOPIC_INFO.SECT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal sectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.TOPIC_ID
     *
     * @return the value of VOTE_TOPIC_INFO.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String effectiveStatus;
    
    public BigDecimal getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.TOPIC_ID
     *
     * @param topicId the value for VOTE_TOPIC_INFO.TOPIC_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setTopicId(BigDecimal topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.TOPIC_NAME
     *
     * @return the value of VOTE_TOPIC_INFO.TOPIC_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.TOPIC_NAME
     *
     * @param topicName the value for VOTE_TOPIC_INFO.TOPIC_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName == null ? null : topicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.TOPIC_CONTENT
     *
     * @return the value of VOTE_TOPIC_INFO.TOPIC_CONTENT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getTopicContent() {
        return topicContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.TOPIC_CONTENT
     *
     * @param topicContent the value for VOTE_TOPIC_INFO.TOPIC_CONTENT
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setTopicContent(String topicContent) {
        this.topicContent = topicContent == null ? null : topicContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.SUM_HS
     *
     * @return the value of VOTE_TOPIC_INFO.SUM_HS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getSumHs() {
        return sumHs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.SUM_HS
     *
     * @param sumHs the value for VOTE_TOPIC_INFO.SUM_HS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setSumHs(BigDecimal sumHs) {
        this.sumHs = sumHs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.SUM_AREA
     *
     * @return the value of VOTE_TOPIC_INFO.SUM_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getSumArea() {
        return sumArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.SUM_AREA
     *
     * @param sumArea the value for VOTE_TOPIC_INFO.SUM_AREA
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setSumArea(BigDecimal sumArea) {
        this.sumArea = sumArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.VOTE_START_DATE
     *
     * @return the value of VOTE_TOPIC_INFO.VOTE_START_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getVoteStartDate() {
        return voteStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.VOTE_START_DATE
     *
     * @param voteStartDate the value for VOTE_TOPIC_INFO.VOTE_START_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setVoteStartDate(String voteStartDate) {
        this.voteStartDate = voteStartDate == null ? null : voteStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.VOTE_END_DATE
     *
     * @return the value of VOTE_TOPIC_INFO.VOTE_END_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getVoteEndDate() {
        return voteEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.VOTE_END_DATE
     *
     * @param voteEndDate the value for VOTE_TOPIC_INFO.VOTE_END_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setVoteEndDate(String voteEndDate) {
        this.voteEndDate = voteEndDate == null ? null : voteEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.VOTE_STATUS
     *
     * @return the value of VOTE_TOPIC_INFO.VOTE_STATUS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getVoteStatus() {
        return voteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.VOTE_STATUS
     *
     * @param voteStatus the value for VOTE_TOPIC_INFO.VOTE_STATUS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setVoteStatus(String voteStatus) {
        this.voteStatus = voteStatus == null ? null : voteStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.REMARK
     *
     * @return the value of VOTE_TOPIC_INFO.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.REMARK
     *
     * @param remark the value for VOTE_TOPIC_INFO.REMARK
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.APPLY_NAME
     *
     * @return the value of VOTE_TOPIC_INFO.APPLY_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getApplyName() {
        return applyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.APPLY_NAME
     *
     * @param applyName the value for VOTE_TOPIC_INFO.APPLY_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setApplyName(String applyName) {
        this.applyName = applyName == null ? null : applyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.LINK_PHONE
     *
     * @return the value of VOTE_TOPIC_INFO.LINK_PHONE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.LINK_PHONE
     *
     * @param linkPhone the value for VOTE_TOPIC_INFO.LINK_PHONE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone == null ? null : linkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.USER_ID
     *
     * @return the value of VOTE_TOPIC_INFO.USER_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.USER_ID
     *
     * @param userId the value for VOTE_TOPIC_INFO.USER_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.ORG_ID
     *
     * @return the value of VOTE_TOPIC_INFO.ORG_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.ORG_ID
     *
     * @param orgId the value for VOTE_TOPIC_INFO.ORG_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.ORG_NAME
     *
     * @return the value of VOTE_TOPIC_INFO.ORG_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.ORG_NAME
     *
     * @param orgName the value for VOTE_TOPIC_INFO.ORG_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.CREATE_DATE
     *
     * @return the value of VOTE_TOPIC_INFO.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.CREATE_DATE
     *
     * @param createDate the value for VOTE_TOPIC_INFO.CREATE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.CREATE_TIME
     *
     * @return the value of VOTE_TOPIC_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.CREATE_TIME
     *
     * @param createTime the value for VOTE_TOPIC_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.LINK_FLAG
     *
     * @return the value of VOTE_TOPIC_INFO.LINK_FLAG
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getLinkFlag() {
        return linkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.LINK_FLAG
     *
     * @param linkFlag the value for VOTE_TOPIC_INFO.LINK_FLAG
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setLinkFlag(String linkFlag) {
        this.linkFlag = linkFlag == null ? null : linkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.WS_ID
     *
     * @return the value of VOTE_TOPIC_INFO.WS_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getWsId() {
        return wsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.WS_ID
     *
     * @param wsId the value for VOTE_TOPIC_INFO.WS_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setWsId(BigDecimal wsId) {
        this.wsId = wsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_TOPIC_INFO.SECT_ID
     *
     * @return the value of VOTE_TOPIC_INFO.SECT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getSectId() {
        return sectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_TOPIC_INFO.SECT_ID
     *
     * @param sectId the value for VOTE_TOPIC_INFO.SECT_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setSectId(BigDecimal sectId) {
        this.sectId = sectId;
    }
    
    public String getEffectiveStatus() {
    	return effectiveStatus;
    }
    
    public void setEffectiveStatus(String effectiveStatus) {
    	this.effectiveStatus = effectiveStatus;
    }
}