package com.indihx.elecvote.entity;

import java.math.BigDecimal;

public class VoteApplyInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.APPLY_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private BigDecimal infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.REGISTE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String registeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.REGISTE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String registeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.OWNER_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String ownerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.CERT_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String certCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.LINK_PHONE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String linkPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.USER_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.USER_PWD
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.PROP_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String propCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VOTE_APPLY_INFO.APPLY_STATUS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    private String applyStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.APPLY_ID
     *
     * @return the value of VOTE_APPLY_INFO.APPLY_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.APPLY_ID
     *
     * @param applyId the value for VOTE_APPLY_INFO.APPLY_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setApplyId(BigDecimal applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.INFO_ID
     *
     * @return the value of VOTE_APPLY_INFO.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public BigDecimal getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.INFO_ID
     *
     * @param infoId the value for VOTE_APPLY_INFO.INFO_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setInfoId(BigDecimal infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.REGISTE_DATE
     *
     * @return the value of VOTE_APPLY_INFO.REGISTE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getRegisteDate() {
        return registeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.REGISTE_DATE
     *
     * @param registeDate the value for VOTE_APPLY_INFO.REGISTE_DATE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setRegisteDate(String registeDate) {
        this.registeDate = registeDate == null ? null : registeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.REGISTE_TIME
     *
     * @return the value of VOTE_APPLY_INFO.REGISTE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getRegisteTime() {
        return registeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.REGISTE_TIME
     *
     * @param registeTime the value for VOTE_APPLY_INFO.REGISTE_TIME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setRegisteTime(String registeTime) {
        this.registeTime = registeTime == null ? null : registeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.OWNER_NAME
     *
     * @return the value of VOTE_APPLY_INFO.OWNER_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.OWNER_NAME
     *
     * @param ownerName the value for VOTE_APPLY_INFO.OWNER_NAME
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.CERT_CODE
     *
     * @return the value of VOTE_APPLY_INFO.CERT_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getCertCode() {
        return certCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.CERT_CODE
     *
     * @param certCode the value for VOTE_APPLY_INFO.CERT_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setCertCode(String certCode) {
        this.certCode = certCode == null ? null : certCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.LINK_PHONE
     *
     * @return the value of VOTE_APPLY_INFO.LINK_PHONE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.LINK_PHONE
     *
     * @param linkPhone the value for VOTE_APPLY_INFO.LINK_PHONE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone == null ? null : linkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.USER_ID
     *
     * @return the value of VOTE_APPLY_INFO.USER_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.USER_ID
     *
     * @param userId the value for VOTE_APPLY_INFO.USER_ID
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.USER_PWD
     *
     * @return the value of VOTE_APPLY_INFO.USER_PWD
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.USER_PWD
     *
     * @param userPwd the value for VOTE_APPLY_INFO.USER_PWD
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.PROP_CODE
     *
     * @return the value of VOTE_APPLY_INFO.PROP_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getPropCode() {
        return propCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.PROP_CODE
     *
     * @param propCode the value for VOTE_APPLY_INFO.PROP_CODE
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setPropCode(String propCode) {
        this.propCode = propCode == null ? null : propCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VOTE_APPLY_INFO.APPLY_STATUS
     *
     * @return the value of VOTE_APPLY_INFO.APPLY_STATUS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VOTE_APPLY_INFO.APPLY_STATUS
     *
     * @param applyStatus the value for VOTE_APPLY_INFO.APPLY_STATUS
     *
     * @mbg.generated Thu Jul 12 18:41:26 CST 2018
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus == null ? null : applyStatus.trim();
    }
}