package com.indihx.elecvote.vo;

import java.math.BigDecimal;

public class HouseInfo {
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.INFO_ID
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private BigDecimal infoId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.INFO_ADDR
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String infoAddr;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.INFO_AREA
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private BigDecimal infoArea;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.OWNER_NAME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String ownerName;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.LINK_PHONE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String linkPhone;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.CERT_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String certCode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.PROP_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String propCode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.DIST_NAME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String distName;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.SECT_ID
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private BigDecimal sectId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.SECT_NAME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String sectName;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.BUILD_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String buildCode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.UNIT_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String unitCode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.FLOOR_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String floorCode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.ROOM_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String roomCode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.HOUSE_ID
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String houseId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.CREATE_DATE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String createDate;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.CREATE_TIME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String createTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.CREATE_WAYS
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String createWays;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.INFO_STATUS
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String infoStatus;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column VOTE_HOUSE_INFO.INFO_REMARK
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String infoRemark;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.INFO_ID
    *
    * @return the value of VOTE_HOUSE_INFO.INFO_ID
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   private String isSelect;
   public String getIsSelect() {
	return isSelect;
	}
	
	public void setIsSelect(String isSelect) {
		this.isSelect = isSelect;
	}
	
	public BigDecimal getInfoId() {
	       return infoId;
	  }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.INFO_ID
    *
    * @param infoId the value for VOTE_HOUSE_INFO.INFO_ID
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setInfoId(BigDecimal infoId) {
       this.infoId = infoId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.INFO_ADDR
    *
    * @return the value of VOTE_HOUSE_INFO.INFO_ADDR
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getInfoAddr() {
       return infoAddr;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.INFO_ADDR
    *
    * @param infoAddr the value for VOTE_HOUSE_INFO.INFO_ADDR
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setInfoAddr(String infoAddr) {
       this.infoAddr = infoAddr == null ? null : infoAddr.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.INFO_AREA
    *
    * @return the value of VOTE_HOUSE_INFO.INFO_AREA
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public BigDecimal getInfoArea() {
       return infoArea;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.INFO_AREA
    *
    * @param infoArea the value for VOTE_HOUSE_INFO.INFO_AREA
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setInfoArea(BigDecimal infoArea) {
       this.infoArea = infoArea;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.OWNER_NAME
    *
    * @return the value of VOTE_HOUSE_INFO.OWNER_NAME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getOwnerName() {
       return ownerName;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.OWNER_NAME
    *
    * @param ownerName the value for VOTE_HOUSE_INFO.OWNER_NAME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setOwnerName(String ownerName) {
       this.ownerName = ownerName == null ? null : ownerName.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.LINK_PHONE
    *
    * @return the value of VOTE_HOUSE_INFO.LINK_PHONE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getLinkPhone() {
       return linkPhone;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.LINK_PHONE
    *
    * @param linkPhone the value for VOTE_HOUSE_INFO.LINK_PHONE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setLinkPhone(String linkPhone) {
       this.linkPhone = linkPhone == null ? null : linkPhone.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.CERT_CODE
    *
    * @return the value of VOTE_HOUSE_INFO.CERT_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getCertCode() {
       return certCode;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.CERT_CODE
    *
    * @param certCode the value for VOTE_HOUSE_INFO.CERT_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setCertCode(String certCode) {
       this.certCode = certCode == null ? null : certCode.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.PROP_CODE
    *
    * @return the value of VOTE_HOUSE_INFO.PROP_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getPropCode() {
       return propCode;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.PROP_CODE
    *
    * @param propCode the value for VOTE_HOUSE_INFO.PROP_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setPropCode(String propCode) {
       this.propCode = propCode == null ? null : propCode.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.DIST_NAME
    *
    * @return the value of VOTE_HOUSE_INFO.DIST_NAME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getDistName() {
       return distName;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.DIST_NAME
    *
    * @param distName the value for VOTE_HOUSE_INFO.DIST_NAME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setDistName(String distName) {
       this.distName = distName == null ? null : distName.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.SECT_ID
    *
    * @return the value of VOTE_HOUSE_INFO.SECT_ID
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public BigDecimal getSectId() {
       return sectId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.SECT_ID
    *
    * @param sectId the value for VOTE_HOUSE_INFO.SECT_ID
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setSectId(BigDecimal sectId) {
       this.sectId = sectId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.SECT_NAME
    *
    * @return the value of VOTE_HOUSE_INFO.SECT_NAME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getSectName() {
       return sectName;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.SECT_NAME
    *
    * @param sectName the value for VOTE_HOUSE_INFO.SECT_NAME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setSectName(String sectName) {
       this.sectName = sectName == null ? null : sectName.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.BUILD_CODE
    *
    * @return the value of VOTE_HOUSE_INFO.BUILD_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getBuildCode() {
       return buildCode;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.BUILD_CODE
    *
    * @param buildCode the value for VOTE_HOUSE_INFO.BUILD_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setBuildCode(String buildCode) {
       this.buildCode = buildCode == null ? null : buildCode.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.UNIT_CODE
    *
    * @return the value of VOTE_HOUSE_INFO.UNIT_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getUnitCode() {
       return unitCode;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.UNIT_CODE
    *
    * @param unitCode the value for VOTE_HOUSE_INFO.UNIT_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setUnitCode(String unitCode) {
       this.unitCode = unitCode == null ? null : unitCode.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.FLOOR_CODE
    *
    * @return the value of VOTE_HOUSE_INFO.FLOOR_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getFloorCode() {
       return floorCode;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.FLOOR_CODE
    *
    * @param floorCode the value for VOTE_HOUSE_INFO.FLOOR_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setFloorCode(String floorCode) {
       this.floorCode = floorCode == null ? null : floorCode.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.ROOM_CODE
    *
    * @return the value of VOTE_HOUSE_INFO.ROOM_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getRoomCode() {
       return roomCode;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.ROOM_CODE
    *
    * @param roomCode the value for VOTE_HOUSE_INFO.ROOM_CODE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setRoomCode(String roomCode) {
       this.roomCode = roomCode == null ? null : roomCode.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.HOUSE_ID
    *
    * @return the value of VOTE_HOUSE_INFO.HOUSE_ID
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getHouseId() {
       return houseId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.HOUSE_ID
    *
    * @param houseId the value for VOTE_HOUSE_INFO.HOUSE_ID
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setHouseId(String houseId) {
       this.houseId = houseId == null ? null : houseId.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.CREATE_DATE
    *
    * @return the value of VOTE_HOUSE_INFO.CREATE_DATE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getCreateDate() {
       return createDate;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.CREATE_DATE
    *
    * @param createDate the value for VOTE_HOUSE_INFO.CREATE_DATE
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setCreateDate(String createDate) {
       this.createDate = createDate == null ? null : createDate.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.CREATE_TIME
    *
    * @return the value of VOTE_HOUSE_INFO.CREATE_TIME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getCreateTime() {
       return createTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.CREATE_TIME
    *
    * @param createTime the value for VOTE_HOUSE_INFO.CREATE_TIME
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setCreateTime(String createTime) {
       this.createTime = createTime == null ? null : createTime.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.CREATE_WAYS
    *
    * @return the value of VOTE_HOUSE_INFO.CREATE_WAYS
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getCreateWays() {
       return createWays;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.CREATE_WAYS
    *
    * @param createWays the value for VOTE_HOUSE_INFO.CREATE_WAYS
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setCreateWays(String createWays) {
       this.createWays = createWays == null ? null : createWays.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.INFO_STATUS
    *
    * @return the value of VOTE_HOUSE_INFO.INFO_STATUS
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getInfoStatus() {
       return infoStatus;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.INFO_STATUS
    *
    * @param infoStatus the value for VOTE_HOUSE_INFO.INFO_STATUS
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setInfoStatus(String infoStatus) {
       this.infoStatus = infoStatus == null ? null : infoStatus.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column VOTE_HOUSE_INFO.INFO_REMARK
    *
    * @return the value of VOTE_HOUSE_INFO.INFO_REMARK
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public String getInfoRemark() {
       return infoRemark;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column VOTE_HOUSE_INFO.INFO_REMARK
    *
    * @param infoRemark the value for VOTE_HOUSE_INFO.INFO_REMARK
    *
    * @mbg.generated Thu Jul 12 18:41:26 CST 2018
    */
   public void setInfoRemark(String infoRemark) {
       this.infoRemark = infoRemark == null ? null : infoRemark.trim();
   }
}
