--------------------------------------------------------
--  文件已创建 - 星期四-十一月-22-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PM_YEAR_BUDGET
--------------------------------------------------------

  CREATE TABLE "VOTE"."PM_YEAR_BUDGET" 
   (	"YEAR_BUDGET_CODE" VARCHAR2(32 BYTE), 
	"IS_NEW_CUST" CHAR(2 BYTE), 
	"CUST_NAME" VARCHAR2(512 BYTE), 
	"SAP_CODE" VARCHAR2(128 BYTE), 
	"PROJECT_NAME" VARCHAR2(256 BYTE), 
	"WBS" VARCHAR2(256 BYTE), 
	"PROJECT_TYPE" CHAR(2 BYTE), 
	"REVEBUE_SOURCE" VARCHAR2(512 BYTE), 
	"COMPANY_ENTITY_NAME" VARCHAR2(128 BYTE), 
	"COMPANY_CODE" VARCHAR2(32 BYTE), 
	"CONTRACT_ID" NUMBER(10,0), 
	"CONTRACT_CODE" VARCHAR2(256 BYTE), 
	"CONTRACT_NAME" VARCHAR2(256 BYTE), 
	"PO_SOW" VARCHAR2(256 BYTE), 
	"CUST_MANAGER_ID" NUMBER(10,0), 
	"CUST_MANAGER_NAME" VARCHAR2(256 BYTE), 
	"TAX_TYPE" CHAR(2 BYTE), 
	"INCOMMING_TYPE" CHAR(2 BYTE), 
	"REGION" CHAR(2 BYTE), 
	"CURRENCY" VARCHAR2(32 BYTE), 
	"GROSS_PROFIT_RATE" NUMBER(10,4), 
	"BUDGET_JAN" NUMBER(10,2), 
	"BUDGET_FEB" NUMBER(10,2), 
	"BUDGET_MAR" NUMBER(10,2), 
	"BUDGET_APR" NUMBER(10,2), 
	"BUDGET_MAY" NUMBER(10,2), 
	"BUDGET_JUN" NUMBER(10,2), 
	"BUDGET_JUL" NUMBER(10,2), 
	"BUDGET_AUG" NUMBER(10,2), 
	"BUDGET_SEP" NUMBER(10,2), 
	"BUDGET_OCT" NUMBER(10,2), 
	"BUDGET_NOV" NUMBER(10,2), 
	"BUDGET_DEC" NUMBER(10,2), 
	"BUDGET_SUM" NUMBER(10,2), 
	"CREATOR_ID" NUMBER(10,0), 
	"CREATE_TIME" VARCHAR2(32 BYTE), 
	"MODIFIER" NUMBER(10,0), 
	"MODIFY_TIME" VARCHAR2(32 BYTE), 
	"IS_DELETE" CHAR(2 BYTE), 
	"REMARK" VARCHAR2(256 BYTE), 
	"REVIEW_STATUS" CHAR(2 BYTE), 
	"BUDGET_YEAR" CHAR(4 BYTE), 
	"REV_RECOGNITION_METHOD" VARCHAR2(32 BYTE), 
	"PRODUCT_LIST" VARCHAR2(128 BYTE), 
	"TAX_RATE" NUMBER(10,4), 
	"CONTRACT_MONEY" NUMBER(10,2), 
	"MANY_YEAR_REV" NUMBER(10,2), 
	"CUR_YEAR_REV" NUMBER(10,2), 
	"LAST_REV" NUMBER(10,2), 
	"AFTER_TAX" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VOTE_USER" ;
 

   COMMENT ON COLUMN "VOTE"."PM_YEAR_BUDGET"."YEAR_BUDGET_CODE" IS '预算code';
 
   COMMENT ON COLUMN "VOTE"."PM_YEAR_BUDGET"."MODIFY_TIME" IS '修改时间';
 
   COMMENT ON COLUMN "VOTE"."PM_YEAR_BUDGET"."IS_DELETE" IS '是否有效';
 
   COMMENT ON COLUMN "VOTE"."PM_YEAR_BUDGET"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "VOTE"."PM_YEAR_BUDGET"."REVIEW_STATUS" IS '评审状态';
REM INSERTING into VOTE.PM_YEAR_BUDGET
SET DEFINE OFF;
Insert into VOTE.PM_YEAR_BUDGET (YEAR_BUDGET_CODE,IS_NEW_CUST,CUST_NAME,SAP_CODE,PROJECT_NAME,WBS,PROJECT_TYPE,REVEBUE_SOURCE,COMPANY_ENTITY_NAME,COMPANY_CODE,CONTRACT_ID,CONTRACT_CODE,CONTRACT_NAME,PO_SOW,CUST_MANAGER_ID,CUST_MANAGER_NAME,TAX_TYPE,INCOMMING_TYPE,REGION,CURRENCY,GROSS_PROFIT_RATE,BUDGET_JAN,BUDGET_FEB,BUDGET_MAR,BUDGET_APR,BUDGET_MAY,BUDGET_JUN,BUDGET_JUL,BUDGET_AUG,BUDGET_SEP,BUDGET_OCT,BUDGET_NOV,BUDGET_DEC,BUDGET_SUM,CREATOR_ID,CREATE_TIME,MODIFIER,MODIFY_TIME,IS_DELETE,REMARK,REVIEW_STATUS,BUDGET_YEAR,REV_RECOGNITION_METHOD,PRODUCT_LIST,TAX_RATE,CONTRACT_MONEY,MANY_YEAR_REV,CUR_YEAR_REV,LAST_REV,AFTER_TAX) values ('YS201811210722',null,'a','sd','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1000,'20181121230844',null,null,'00',null,null,null,null,null,null,null,null,null,null,null);
Insert into VOTE.PM_YEAR_BUDGET (YEAR_BUDGET_CODE,IS_NEW_CUST,CUST_NAME,SAP_CODE,PROJECT_NAME,WBS,PROJECT_TYPE,REVEBUE_SOURCE,COMPANY_ENTITY_NAME,COMPANY_CODE,CONTRACT_ID,CONTRACT_CODE,CONTRACT_NAME,PO_SOW,CUST_MANAGER_ID,CUST_MANAGER_NAME,TAX_TYPE,INCOMMING_TYPE,REGION,CURRENCY,GROSS_PROFIT_RATE,BUDGET_JAN,BUDGET_FEB,BUDGET_MAR,BUDGET_APR,BUDGET_MAY,BUDGET_JUN,BUDGET_JUL,BUDGET_AUG,BUDGET_SEP,BUDGET_OCT,BUDGET_NOV,BUDGET_DEC,BUDGET_SUM,CREATOR_ID,CREATE_TIME,MODIFIER,MODIFY_TIME,IS_DELETE,REMARK,REVIEW_STATUS,BUDGET_YEAR,REV_RECOGNITION_METHOD,PRODUCT_LIST,TAX_RATE,CONTRACT_MONEY,MANY_YEAR_REV,CUR_YEAR_REV,LAST_REV,AFTER_TAX) values ('YS201811215511',null,'as','sda','2',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1000,'20181121230844',null,null,'00',null,null,null,null,null,null,null,null,null,null,null);
Insert into VOTE.PM_YEAR_BUDGET (YEAR_BUDGET_CODE,IS_NEW_CUST,CUST_NAME,SAP_CODE,PROJECT_NAME,WBS,PROJECT_TYPE,REVEBUE_SOURCE,COMPANY_ENTITY_NAME,COMPANY_CODE,CONTRACT_ID,CONTRACT_CODE,CONTRACT_NAME,PO_SOW,CUST_MANAGER_ID,CUST_MANAGER_NAME,TAX_TYPE,INCOMMING_TYPE,REGION,CURRENCY,GROSS_PROFIT_RATE,BUDGET_JAN,BUDGET_FEB,BUDGET_MAR,BUDGET_APR,BUDGET_MAY,BUDGET_JUN,BUDGET_JUL,BUDGET_AUG,BUDGET_SEP,BUDGET_OCT,BUDGET_NOV,BUDGET_DEC,BUDGET_SUM,CREATOR_ID,CREATE_TIME,MODIFIER,MODIFY_TIME,IS_DELETE,REMARK,REVIEW_STATUS,BUDGET_YEAR,REV_RECOGNITION_METHOD,PRODUCT_LIST,TAX_RATE,CONTRACT_MONEY,MANY_YEAR_REV,CUR_YEAR_REV,LAST_REV,AFTER_TAX) values ('YS201811211500',null,'d','da','3',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1000,'20181121230844',null,null,'00',null,null,null,null,null,null,null,null,null,null,null);
Insert into VOTE.PM_YEAR_BUDGET (YEAR_BUDGET_CODE,IS_NEW_CUST,CUST_NAME,SAP_CODE,PROJECT_NAME,WBS,PROJECT_TYPE,REVEBUE_SOURCE,COMPANY_ENTITY_NAME,COMPANY_CODE,CONTRACT_ID,CONTRACT_CODE,CONTRACT_NAME,PO_SOW,CUST_MANAGER_ID,CUST_MANAGER_NAME,TAX_TYPE,INCOMMING_TYPE,REGION,CURRENCY,GROSS_PROFIT_RATE,BUDGET_JAN,BUDGET_FEB,BUDGET_MAR,BUDGET_APR,BUDGET_MAY,BUDGET_JUN,BUDGET_JUL,BUDGET_AUG,BUDGET_SEP,BUDGET_OCT,BUDGET_NOV,BUDGET_DEC,BUDGET_SUM,CREATOR_ID,CREATE_TIME,MODIFIER,MODIFY_TIME,IS_DELETE,REMARK,REVIEW_STATUS,BUDGET_YEAR,REV_RECOGNITION_METHOD,PRODUCT_LIST,TAX_RATE,CONTRACT_MONEY,MANY_YEAR_REV,CUR_YEAR_REV,LAST_REV,AFTER_TAX) values ('YS201811212199',null,'a','asd','4',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1000,'20181121230844',null,null,'00',null,null,null,null,null,null,null,null,null,null,null);
Insert into VOTE.PM_YEAR_BUDGET (YEAR_BUDGET_CODE,IS_NEW_CUST,CUST_NAME,SAP_CODE,PROJECT_NAME,WBS,PROJECT_TYPE,REVEBUE_SOURCE,COMPANY_ENTITY_NAME,COMPANY_CODE,CONTRACT_ID,CONTRACT_CODE,CONTRACT_NAME,PO_SOW,CUST_MANAGER_ID,CUST_MANAGER_NAME,TAX_TYPE,INCOMMING_TYPE,REGION,CURRENCY,GROSS_PROFIT_RATE,BUDGET_JAN,BUDGET_FEB,BUDGET_MAR,BUDGET_APR,BUDGET_MAY,BUDGET_JUN,BUDGET_JUL,BUDGET_AUG,BUDGET_SEP,BUDGET_OCT,BUDGET_NOV,BUDGET_DEC,BUDGET_SUM,CREATOR_ID,CREATE_TIME,MODIFIER,MODIFY_TIME,IS_DELETE,REMARK,REVIEW_STATUS,BUDGET_YEAR,REV_RECOGNITION_METHOD,PRODUCT_LIST,TAX_RATE,CONTRACT_MONEY,MANY_YEAR_REV,CUR_YEAR_REV,LAST_REV,AFTER_TAX) values ('YS201811215125',null,'as','da','5',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1000,'20181121230844',null,null,'00',null,null,null,null,null,null,null,null,null,null,null);
Insert into VOTE.PM_YEAR_BUDGET (YEAR_BUDGET_CODE,IS_NEW_CUST,CUST_NAME,SAP_CODE,PROJECT_NAME,WBS,PROJECT_TYPE,REVEBUE_SOURCE,COMPANY_ENTITY_NAME,COMPANY_CODE,CONTRACT_ID,CONTRACT_CODE,CONTRACT_NAME,PO_SOW,CUST_MANAGER_ID,CUST_MANAGER_NAME,TAX_TYPE,INCOMMING_TYPE,REGION,CURRENCY,GROSS_PROFIT_RATE,BUDGET_JAN,BUDGET_FEB,BUDGET_MAR,BUDGET_APR,BUDGET_MAY,BUDGET_JUN,BUDGET_JUL,BUDGET_AUG,BUDGET_SEP,BUDGET_OCT,BUDGET_NOV,BUDGET_DEC,BUDGET_SUM,CREATOR_ID,CREATE_TIME,MODIFIER,MODIFY_TIME,IS_DELETE,REMARK,REVIEW_STATUS,BUDGET_YEAR,REV_RECOGNITION_METHOD,PRODUCT_LIST,TAX_RATE,CONTRACT_MONEY,MANY_YEAR_REV,CUR_YEAR_REV,LAST_REV,AFTER_TAX) values ('YS201811215605',null,'a','asd','6',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1000,'20181121230844',null,null,'00',null,null,null,null,null,null,null,null,null,null,null);
Insert into VOTE.PM_YEAR_BUDGET (YEAR_BUDGET_CODE,IS_NEW_CUST,CUST_NAME,SAP_CODE,PROJECT_NAME,WBS,PROJECT_TYPE,REVEBUE_SOURCE,COMPANY_ENTITY_NAME,COMPANY_CODE,CONTRACT_ID,CONTRACT_CODE,CONTRACT_NAME,PO_SOW,CUST_MANAGER_ID,CUST_MANAGER_NAME,TAX_TYPE,INCOMMING_TYPE,REGION,CURRENCY,GROSS_PROFIT_RATE,BUDGET_JAN,BUDGET_FEB,BUDGET_MAR,BUDGET_APR,BUDGET_MAY,BUDGET_JUN,BUDGET_JUL,BUDGET_AUG,BUDGET_SEP,BUDGET_OCT,BUDGET_NOV,BUDGET_DEC,BUDGET_SUM,CREATOR_ID,CREATE_TIME,MODIFIER,MODIFY_TIME,IS_DELETE,REMARK,REVIEW_STATUS,BUDGET_YEAR,REV_RECOGNITION_METHOD,PRODUCT_LIST,TAX_RATE,CONTRACT_MONEY,MANY_YEAR_REV,CUR_YEAR_REV,LAST_REV,AFTER_TAX) values ('YS201811213056',null,'sd','asd','7',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1000,'20181121230844',null,null,'00',null,null,null,null,null,null,null,null,null,null,null);
Insert into VOTE.PM_YEAR_BUDGET (YEAR_BUDGET_CODE,IS_NEW_CUST,CUST_NAME,SAP_CODE,PROJECT_NAME,WBS,PROJECT_TYPE,REVEBUE_SOURCE,COMPANY_ENTITY_NAME,COMPANY_CODE,CONTRACT_ID,CONTRACT_CODE,CONTRACT_NAME,PO_SOW,CUST_MANAGER_ID,CUST_MANAGER_NAME,TAX_TYPE,INCOMMING_TYPE,REGION,CURRENCY,GROSS_PROFIT_RATE,BUDGET_JAN,BUDGET_FEB,BUDGET_MAR,BUDGET_APR,BUDGET_MAY,BUDGET_JUN,BUDGET_JUL,BUDGET_AUG,BUDGET_SEP,BUDGET_OCT,BUDGET_NOV,BUDGET_DEC,BUDGET_SUM,CREATOR_ID,CREATE_TIME,MODIFIER,MODIFY_TIME,IS_DELETE,REMARK,REVIEW_STATUS,BUDGET_YEAR,REV_RECOGNITION_METHOD,PRODUCT_LIST,TAX_RATE,CONTRACT_MONEY,MANY_YEAR_REV,CUR_YEAR_REV,LAST_REV,AFTER_TAX) values ('YS201811213580',null,'d','sdas','8',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1000,'20181121230844',null,null,'00',null,null,null,null,null,null,null,null,null,null,null);
--------------------------------------------------------
--  DDL for Index PM_YEAR_BUDGET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VOTE"."PM_YEAR_BUDGET_PK" ON "VOTE"."PM_YEAR_BUDGET" ("YEAR_BUDGET_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VOTE_USER" ;
--------------------------------------------------------
--  Constraints for Table PM_YEAR_BUDGET
--------------------------------------------------------

  ALTER TABLE "VOTE"."PM_YEAR_BUDGET" ADD CONSTRAINT "PM_YEAR_BUDGET_PK" PRIMARY KEY ("YEAR_BUDGET_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VOTE_USER"  ENABLE;
